/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface IPriceConsumerInterface extends Interface {
    getFunction(nameOrSignature: "decimals" | "getCentPriceInWei" | "getPriceFeed" | "getRC" | "setPriceFeed"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'decimals', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getCentPriceInWei', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getPriceFeed', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRC', values?: undefined): string;
encodeFunctionData(functionFragment: 'setPriceFeed', values: [BigNumberish, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'decimals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCentPriceInWei', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPriceFeed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRC', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPriceFeed', data: BytesLike): Result;
  }

  

  export interface IPriceConsumer extends BaseContract {
    
    connect(runner?: ContractRunner | null): IPriceConsumer;
    waitForDeployment(): Promise<this>;

    interface: IPriceConsumerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    decimals: TypedContractMethod<
      [quote: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getCentPriceInWei: TypedContractMethod<
      [seq: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getPriceFeed: TypedContractMethod<
      [seq: BigNumberish, ],
      [string],
      'view'
    >
    

    
    getRC: TypedContractMethod<
      [],
      [string],
      'nonpayable'
    >
    

    
    setPriceFeed: TypedContractMethod<
      [seq: BigNumberish, _feed: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'decimals'): TypedContractMethod<
      [quote: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getCentPriceInWei'): TypedContractMethod<
      [seq: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getPriceFeed'): TypedContractMethod<
      [seq: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getRC'): TypedContractMethod<
      [],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setPriceFeed'): TypedContractMethod<
      [seq: BigNumberish, _feed: AddressLike, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }