/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace DealsRepo {
      
    export type HeadStruct = {typeOfDeal: BigNumberish, seqOfDeal: BigNumberish, preSeq: BigNumberish, classOfShare: BigNumberish, seqOfShare: BigNumberish, seller: BigNumberish, priceOfPaid: BigNumberish, priceOfPar: BigNumberish, closingDeadline: BigNumberish, votingWeight: BigNumberish}

    export type HeadStructOutput = [typeOfDeal: bigint, seqOfDeal: bigint, preSeq: bigint, classOfShare: bigint, seqOfShare: bigint, seller: bigint, priceOfPaid: bigint, priceOfPar: bigint, closingDeadline: bigint, votingWeight: bigint] & {typeOfDeal: bigint, seqOfDeal: bigint, preSeq: bigint, classOfShare: bigint, seqOfShare: bigint, seller: bigint, priceOfPaid: bigint, priceOfPar: bigint, closingDeadline: bigint, votingWeight: bigint }
  
    }

  export interface DealsRepoInterface extends Interface {
    getFunction(nameOrSignature: "codifyHead" | "snParser"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'codifyHead', values: [DealsRepo.HeadStruct]): string;
encodeFunctionData(functionFragment: 'snParser', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'codifyHead', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'snParser', data: BytesLike): Result;
  }

  

  export interface DealsRepo extends BaseContract {
    
    connect(runner?: ContractRunner | null): DealsRepo;
    waitForDeployment(): Promise<this>;

    interface: DealsRepoInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    codifyHead: TypedContractMethod<
      [head: DealsRepo.HeadStruct, ],
      [string],
      'view'
    >
    

    
    snParser: TypedContractMethod<
      [sn: BytesLike, ],
      [DealsRepo.HeadStructOutput],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'codifyHead'): TypedContractMethod<
      [head: DealsRepo.HeadStruct, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'snParser'): TypedContractMethod<
      [sn: BytesLike, ],
      [DealsRepo.HeadStructOutput],
      'view'
    >;

    

    filters: {
      
    };
  }