/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace SwapsRepo {
      
    export type SwapStruct = {seqOfSwap: BigNumberish, seqOfPledge: BigNumberish, paidOfPledge: BigNumberish, seqOfTarget: BigNumberish, paidOfTarget: BigNumberish, priceOfDeal: BigNumberish, isPutOpt: boolean, state: BigNumberish}

    export type SwapStructOutput = [seqOfSwap: bigint, seqOfPledge: bigint, paidOfPledge: bigint, seqOfTarget: bigint, paidOfTarget: bigint, priceOfDeal: bigint, isPutOpt: boolean, state: bigint] & {seqOfSwap: bigint, seqOfPledge: bigint, paidOfPledge: bigint, seqOfTarget: bigint, paidOfTarget: bigint, priceOfDeal: bigint, isPutOpt: boolean, state: bigint }
  
    }

  export interface SwapsRepoInterface extends Interface {
    getFunction(nameOrSignature: "codifySwap"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'codifySwap', values: [SwapsRepo.SwapStruct]): string;

    decodeFunctionResult(functionFragment: 'codifySwap', data: BytesLike): Result;
  }

  

  export interface SwapsRepo extends BaseContract {
    
    connect(runner?: ContractRunner | null): SwapsRepo;
    waitForDeployment(): Promise<this>;

    interface: SwapsRepoInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    codifySwap: TypedContractMethod<
      [swap: SwapsRepo.SwapStruct, ],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'codifySwap'): TypedContractMethod<
      [swap: SwapsRepo.SwapStruct, ],
      [string],
      'view'
    >;

    

    filters: {
      
    };
  }