/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../../../common.js"
  
export declare namespace RulesParser {
      
    export type VotingRuleStruct = {seqOfRule: BigNumberish, qtyOfSubRule: BigNumberish, seqOfSubRule: BigNumberish, authority: BigNumberish, headRatio: BigNumberish, amountRatio: BigNumberish, onlyAttendance: boolean, impliedConsent: boolean, partyAsConsent: boolean, againstShallBuy: boolean, frExecDays: BigNumberish, dtExecDays: BigNumberish, dtConfirmDays: BigNumberish, invExitDays: BigNumberish, votePrepareDays: BigNumberish, votingDays: BigNumberish, execDaysForPutOpt: BigNumberish, vetoers: [BigNumberish, BigNumberish], class: BigNumberish}

    export type VotingRuleStructOutput = [seqOfRule: bigint, qtyOfSubRule: bigint, seqOfSubRule: bigint, authority: bigint, headRatio: bigint, amountRatio: bigint, onlyAttendance: boolean, impliedConsent: boolean, partyAsConsent: boolean, againstShallBuy: boolean, frExecDays: bigint, dtExecDays: bigint, dtConfirmDays: bigint, invExitDays: bigint, votePrepareDays: bigint, votingDays: bigint, execDaysForPutOpt: bigint, vetoers: [bigint, bigint], class_: bigint] & {seqOfRule: bigint, qtyOfSubRule: bigint, seqOfSubRule: bigint, authority: bigint, headRatio: bigint, amountRatio: bigint, onlyAttendance: boolean, impliedConsent: boolean, partyAsConsent: boolean, againstShallBuy: boolean, frExecDays: bigint, dtExecDays: bigint, dtConfirmDays: bigint, invExitDays: bigint, votePrepareDays: bigint, votingDays: bigint, execDaysForPutOpt: bigint, vetoers: [bigint, bigint], class: bigint }
  
    }

export declare namespace FilesRepo {
      
    export type HeadStruct = {circulateDate: BigNumberish, signingDays: BigNumberish, closingDays: BigNumberish, seqOfVR: BigNumberish, frExecDays: BigNumberish, dtExecDays: BigNumberish, dtConfirmDays: BigNumberish, proposeDate: BigNumberish, invExitDays: BigNumberish, votePrepareDays: BigNumberish, votingDays: BigNumberish, execDaysForPutOpt: BigNumberish, seqOfMotion: BigNumberish, state: BigNumberish}

    export type HeadStructOutput = [circulateDate: bigint, signingDays: bigint, closingDays: bigint, seqOfVR: bigint, frExecDays: bigint, dtExecDays: bigint, dtConfirmDays: bigint, proposeDate: bigint, invExitDays: bigint, votePrepareDays: bigint, votingDays: bigint, execDaysForPutOpt: bigint, seqOfMotion: bigint, state: bigint] & {circulateDate: bigint, signingDays: bigint, closingDays: bigint, seqOfVR: bigint, frExecDays: bigint, dtExecDays: bigint, dtConfirmDays: bigint, proposeDate: bigint, invExitDays: bigint, votePrepareDays: bigint, votingDays: bigint, execDaysForPutOpt: bigint, seqOfMotion: bigint, state: bigint }
  

    export type RefStruct = {docUrl: BytesLike, docHash: BytesLike}

    export type RefStructOutput = [docUrl: string, docHash: string] & {docUrl: string, docHash: string }
  

    export type FileStruct = {snOfDoc: BytesLike, head: FilesRepo.HeadStruct, ref: FilesRepo.RefStruct}

    export type FileStructOutput = [snOfDoc: string, head: FilesRepo.HeadStructOutput, ref: FilesRepo.RefStructOutput] & {snOfDoc: string, head: FilesRepo.HeadStructOutput, ref: FilesRepo.RefStructOutput }
  
    }

  export interface IRegisterOfConstitutionInterface extends Interface {
    getFunction(nameOrSignature: "changePointer" | "circulateFile" | "closingDeadline" | "dtExecDeadline" | "execFile" | "frExecDeadline" | "getFile" | "getFilesList" | "getHeadOfFile" | "isRegistered" | "pointer" | "proposeFile" | "qtyOfFiles" | "regFile" | "setStateOfFile" | "signingDeadline" | "terminateFile" | "terminateStartpoint" | "voteCountingForFile" | "votingDeadline"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ChangePointer" | "UpdateStateOfFile"): EventFragment;

    encodeFunctionData(functionFragment: 'changePointer', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'circulateFile', values: [AddressLike, BigNumberish, BigNumberish, RulesParser.VotingRuleStruct, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'closingDeadline', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'dtExecDeadline', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'execFile', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'frExecDeadline', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getFile', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getFilesList', values?: undefined): string;
encodeFunctionData(functionFragment: 'getHeadOfFile', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isRegistered', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'pointer', values?: undefined): string;
encodeFunctionData(functionFragment: 'proposeFile', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'qtyOfFiles', values?: undefined): string;
encodeFunctionData(functionFragment: 'regFile', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'setStateOfFile', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'signingDeadline', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'terminateFile', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'terminateStartpoint', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'voteCountingForFile', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'votingDeadline', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'changePointer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'circulateFile', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'closingDeadline', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'dtExecDeadline', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'execFile', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'frExecDeadline', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getFile', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getFilesList', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getHeadOfFile', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isRegistered', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pointer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposeFile', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'qtyOfFiles', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'regFile', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setStateOfFile', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'signingDeadline', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'terminateFile', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'terminateStartpoint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'voteCountingForFile', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'votingDeadline', data: BytesLike): Result;
  }

  
    export namespace ChangePointerEvent {
      export type InputTuple = [pointer: AddressLike];
      export type OutputTuple = [pointer: string];
      export interface OutputObject {pointer: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UpdateStateOfFileEvent {
      export type InputTuple = [body: AddressLike, state: BigNumberish];
      export type OutputTuple = [body: string, state: bigint];
      export interface OutputObject {body: string, state: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface IRegisterOfConstitution extends BaseContract {
    
    connect(runner?: ContractRunner | null): IRegisterOfConstitution;
    waitForDeployment(): Promise<this>;

    interface: IRegisterOfConstitutionInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    changePointer: TypedContractMethod<
      [body: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    circulateFile: TypedContractMethod<
      [body: AddressLike, signingDays: BigNumberish, closingDays: BigNumberish, vr: RulesParser.VotingRuleStruct, docUrl: BytesLike, docHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    closingDeadline: TypedContractMethod<
      [body: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    dtExecDeadline: TypedContractMethod<
      [body: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    execFile: TypedContractMethod<
      [body: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    frExecDeadline: TypedContractMethod<
      [body: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getFile: TypedContractMethod<
      [body: AddressLike, ],
      [FilesRepo.FileStructOutput],
      'view'
    >
    

    
    getFilesList: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    getHeadOfFile: TypedContractMethod<
      [body: AddressLike, ],
      [FilesRepo.HeadStructOutput],
      'view'
    >
    

    
    isRegistered: TypedContractMethod<
      [body: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    pointer: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    proposeFile: TypedContractMethod<
      [body: AddressLike, seqOfMotion: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    qtyOfFiles: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    regFile: TypedContractMethod<
      [snOfDoc: BytesLike, body: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setStateOfFile: TypedContractMethod<
      [body: AddressLike, state: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    signingDeadline: TypedContractMethod<
      [body: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    terminateFile: TypedContractMethod<
      [body: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    terminateStartpoint: TypedContractMethod<
      [body: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    voteCountingForFile: TypedContractMethod<
      [body: AddressLike, approved: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    votingDeadline: TypedContractMethod<
      [body: AddressLike, ],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'changePointer'): TypedContractMethod<
      [body: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'circulateFile'): TypedContractMethod<
      [body: AddressLike, signingDays: BigNumberish, closingDays: BigNumberish, vr: RulesParser.VotingRuleStruct, docUrl: BytesLike, docHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'closingDeadline'): TypedContractMethod<
      [body: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'dtExecDeadline'): TypedContractMethod<
      [body: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'execFile'): TypedContractMethod<
      [body: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'frExecDeadline'): TypedContractMethod<
      [body: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getFile'): TypedContractMethod<
      [body: AddressLike, ],
      [FilesRepo.FileStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getFilesList'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getHeadOfFile'): TypedContractMethod<
      [body: AddressLike, ],
      [FilesRepo.HeadStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'isRegistered'): TypedContractMethod<
      [body: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'pointer'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'proposeFile'): TypedContractMethod<
      [body: AddressLike, seqOfMotion: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'qtyOfFiles'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'regFile'): TypedContractMethod<
      [snOfDoc: BytesLike, body: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setStateOfFile'): TypedContractMethod<
      [body: AddressLike, state: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'signingDeadline'): TypedContractMethod<
      [body: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'terminateFile'): TypedContractMethod<
      [body: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'terminateStartpoint'): TypedContractMethod<
      [body: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'voteCountingForFile'): TypedContractMethod<
      [body: AddressLike, approved: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'votingDeadline'): TypedContractMethod<
      [body: AddressLike, ],
      [bigint],
      'view'
    >;

    getEvent(key: 'ChangePointer'): TypedContractEvent<ChangePointerEvent.InputTuple, ChangePointerEvent.OutputTuple, ChangePointerEvent.OutputObject>;
getEvent(key: 'UpdateStateOfFile'): TypedContractEvent<UpdateStateOfFileEvent.InputTuple, UpdateStateOfFileEvent.OutputTuple, UpdateStateOfFileEvent.OutputObject>;

    filters: {
      
      'ChangePointer(address)': TypedContractEvent<ChangePointerEvent.InputTuple, ChangePointerEvent.OutputTuple, ChangePointerEvent.OutputObject>;
      ChangePointer: TypedContractEvent<ChangePointerEvent.InputTuple, ChangePointerEvent.OutputTuple, ChangePointerEvent.OutputObject>;
    

      'UpdateStateOfFile(address,uint256)': TypedContractEvent<UpdateStateOfFileEvent.InputTuple, UpdateStateOfFileEvent.OutputTuple, UpdateStateOfFileEvent.OutputObject>;
      UpdateStateOfFile: TypedContractEvent<UpdateStateOfFileEvent.InputTuple, UpdateStateOfFileEvent.OutputTuple, UpdateStateOfFileEvent.OutputObject>;
    
    };
  }