/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IGMMKeeper, IGMMKeeperInterface } from "../../../comps/keepers/IGMMKeeper.js";

  const _abi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "targets",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "values",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "bytes",
        "name": "params",
        "type": "bytes"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "seqOfMotion",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "caller",
        "type": "uint256"
      }
    ],
    "name": "ExecAction",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfMotion",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "attitude",
        "type": "uint256"
      },
      {
        "internalType": "bytes32",
        "name": "sigHash",
        "type": "bytes32"
      },
      {
        "internalType": "address",
        "name": "msgSender",
        "type": "address"
      }
    ],
    "name": "castVoteOfGM",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfVR",
        "type": "uint256"
      },
      {
        "internalType": "address[]",
        "name": "targets",
        "type": "address[]"
      },
      {
        "internalType": "uint256[]",
        "name": "values",
        "type": "uint256[]"
      },
      {
        "internalType": "bytes[]",
        "name": "params",
        "type": "bytes[]"
      },
      {
        "internalType": "bytes32",
        "name": "desHash",
        "type": "bytes32"
      },
      {
        "internalType": "uint256",
        "name": "executor",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "msgSender",
        "type": "address"
      }
    ],
    "name": "createActionOfGM",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfPos",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "msgSender",
        "type": "address"
      }
    ],
    "name": "createMotionToRemoveDirector",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "receiver",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "seqOfMotion",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "msgSender",
        "type": "address"
      }
    ],
    "name": "deprecateGK",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfMotion",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "delegate",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "msgSender",
        "type": "address"
      }
    ],
    "name": "entrustDelegaterForGeneralMeeting",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "typeOfAction",
        "type": "uint256"
      },
      {
        "internalType": "address[]",
        "name": "targets",
        "type": "address[]"
      },
      {
        "internalType": "uint256[]",
        "name": "values",
        "type": "uint256[]"
      },
      {
        "internalType": "bytes[]",
        "name": "params",
        "type": "bytes[]"
      },
      {
        "internalType": "bytes32",
        "name": "desHash",
        "type": "bytes32"
      },
      {
        "internalType": "uint256",
        "name": "seqOfMotion",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "msgSender",
        "type": "address"
      }
    ],
    "name": "execActionOfGM",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfPos",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "candidate",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "msgSender",
        "type": "address"
      }
    ],
    "name": "nominateDirector",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "doc",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "seqOfVR",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "executor",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "msgSender",
        "type": "address"
      }
    ],
    "name": "proposeDocOfGM",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfMotion",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "msgSender",
        "type": "address"
      }
    ],
    "name": "proposeMotionToGeneralMeeting",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "receiver",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "msgSender",
        "type": "address"
      }
    ],
    "name": "proposeToDeprecateGK",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "amt",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "expireDate",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "seqOfVR",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "seqOfDR",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "para",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "executor",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "msgSender",
        "type": "address"
      }
    ],
    "name": "proposeToDistributeUsd",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "internalType": "bool",
        "name": "isCBP",
        "type": "bool"
      },
      {
        "internalType": "uint256",
        "name": "amt",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "expireDate",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "seqOfVR",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "executor",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "msgSender",
        "type": "address"
      }
    ],
    "name": "proposeToTransferFund",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfMotion",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "msgSender",
        "type": "address"
      }
    ],
    "name": "voteCountingOfGM",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IGMMKeeper__factory {
    static readonly abi = _abi;
    static createInterface(): IGMMKeeperInterface {
      return new Interface(_abi) as IGMMKeeperInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IGMMKeeper {
      return new Contract(address, _abi, runner) as unknown as IGMMKeeper;
    }
  }
  