/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { CoreKeeper, CoreKeeperInterface } from "../../../comps/modules/CoreKeeper.js";

  const _abi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "receiver",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "balanceOfCBP",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "balanceOfETH",
        "type": "uint256"
      }
    ],
    "name": "DeprecateGK",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "contents",
        "type": "uint256"
      }
    ],
    "name": "ExecAction",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "from",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "amt",
        "type": "uint256"
      }
    ],
    "name": "ReceivedCash",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "title",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "book",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "dk",
        "type": "address"
      }
    ],
    "name": "RegBook",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "title",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "keeper",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "dk",
        "type": "address"
      }
    ],
    "name": "RegKeeper",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "keeper",
        "type": "address"
      }
    ],
    "name": "SetDirectKeeper",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "gk",
        "type": "address"
      }
    ],
    "name": "SetNewGK",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "owner",
        "type": "address"
      }
    ],
    "name": "SetNewOwner",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "sigHash",
        "type": "bytes32"
      }
    ],
    "name": "acceptSHA",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "body",
        "type": "address"
      }
    ],
    "name": "activateSHA",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "userNo",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "seqOfLR",
        "type": "uint256"
      }
    ],
    "name": "approveInvestor",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfMotion",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "attitude",
        "type": "uint256"
      },
      {
        "internalType": "bytes32",
        "name": "sigHash",
        "type": "bytes32"
      }
    ],
    "name": "castVote",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfMotion",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "attitude",
        "type": "uint256"
      },
      {
        "internalType": "bytes32",
        "name": "sigHash",
        "type": "bytes32"
      }
    ],
    "name": "castVoteOfGM",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "body",
        "type": "address"
      },
      {
        "internalType": "bytes32",
        "name": "docUrl",
        "type": "bytes32"
      },
      {
        "internalType": "bytes32",
        "name": "docHash",
        "type": "bytes32"
      }
    ],
    "name": "circulateIA",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "body",
        "type": "address"
      },
      {
        "internalType": "bytes32",
        "name": "docUrl",
        "type": "bytes32"
      },
      {
        "internalType": "bytes32",
        "name": "docHash",
        "type": "bytes32"
      }
    ],
    "name": "circulateSHA",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "ia",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "seqOfDeal",
        "type": "uint256"
      },
      {
        "internalType": "string",
        "name": "hashKey",
        "type": "string"
      }
    ],
    "name": "closeDeal",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfVR",
        "type": "uint256"
      },
      {
        "internalType": "address[]",
        "name": "targets",
        "type": "address[]"
      },
      {
        "internalType": "uint256[]",
        "name": "values",
        "type": "uint256[]"
      },
      {
        "internalType": "bytes[]",
        "name": "params",
        "type": "bytes[]"
      },
      {
        "internalType": "bytes32",
        "name": "desHash",
        "type": "bytes32"
      },
      {
        "internalType": "uint256",
        "name": "executor",
        "type": "uint256"
      }
    ],
    "name": "createAction",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfVR",
        "type": "uint256"
      },
      {
        "internalType": "address[]",
        "name": "targets",
        "type": "address[]"
      },
      {
        "internalType": "uint256[]",
        "name": "values",
        "type": "uint256[]"
      },
      {
        "internalType": "bytes[]",
        "name": "params",
        "type": "bytes[]"
      },
      {
        "internalType": "bytes32",
        "name": "desHash",
        "type": "bytes32"
      },
      {
        "internalType": "uint256",
        "name": "executor",
        "type": "uint256"
      }
    ],
    "name": "createActionOfGM",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "createCorpSeal",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "snOfIA",
        "type": "uint256"
      }
    ],
    "name": "createIA",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "doc",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "seqOfVR",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "executor",
        "type": "uint256"
      }
    ],
    "name": "createMotionToApproveDoc",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfPos",
        "type": "uint256"
      }
    ],
    "name": "createMotionToRemoveDirector",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfPos",
        "type": "uint256"
      }
    ],
    "name": "createMotionToRemoveOfficer",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "snOfPld",
        "type": "bytes32"
      },
      {
        "internalType": "uint256",
        "name": "paid",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "par",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "guaranteedAmt",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "execDays",
        "type": "uint256"
      }
    ],
    "name": "createPledge",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "version",
        "type": "uint256"
      }
    ],
    "name": "createSHA",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address payable",
        "name": "receiver",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "seqOfMotion",
        "type": "uint256"
      }
    ],
    "name": "deprecateGK",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "amt",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "expireDate",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "seqOfDR",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "fundManager",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "seqOfMotion",
        "type": "uint256"
      }
    ],
    "name": "distributeIncome",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "amt",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "expireDate",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "seqOfDR",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "seqOfMotion",
        "type": "uint256"
      }
    ],
    "name": "distributeProfits",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfMotion",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "delegate",
        "type": "uint256"
      }
    ],
    "name": "entrustDelegaterForBoardMeeting",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfMotion",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "delegate",
        "type": "uint256"
      }
    ],
    "name": "entrustDelegaterForGeneralMeeting",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "typeOfAction",
        "type": "uint256"
      },
      {
        "internalType": "address[]",
        "name": "targets",
        "type": "address[]"
      },
      {
        "internalType": "uint256[]",
        "name": "values",
        "type": "uint256[]"
      },
      {
        "internalType": "bytes[]",
        "name": "params",
        "type": "bytes[]"
      },
      {
        "internalType": "bytes32",
        "name": "desHash",
        "type": "bytes32"
      },
      {
        "internalType": "uint256",
        "name": "seqOfMotion",
        "type": "uint256"
      }
    ],
    "name": "execAction",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfVR",
        "type": "uint256"
      },
      {
        "internalType": "address[]",
        "name": "targets",
        "type": "address[]"
      },
      {
        "internalType": "uint256[]",
        "name": "values",
        "type": "uint256[]"
      },
      {
        "internalType": "bytes[]",
        "name": "params",
        "type": "bytes[]"
      },
      {
        "internalType": "bytes32",
        "name": "desHash",
        "type": "bytes32"
      },
      {
        "internalType": "uint256",
        "name": "seqOfMotion",
        "type": "uint256"
      }
    ],
    "name": "execActionOfGM",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfShare",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "seqOfPld",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "buyer",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "groupOfBuyer",
        "type": "uint256"
      }
    ],
    "name": "execPledge",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfShare",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "seqOfPld",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "extDays",
        "type": "uint256"
      }
    ],
    "name": "extendPledge",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfLR",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "seqOfShare",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "paid",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "addrTo",
        "type": "address"
      },
      {
        "internalType": "bytes32",
        "name": "hashOrder",
        "type": "bytes32"
      }
    ],
    "name": "forceTransfer",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfLR",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "seqOfShare",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "paid",
        "type": "uint256"
      },
      {
        "internalType": "bytes32",
        "name": "hashOrder",
        "type": "bytes32"
      }
    ],
    "name": "freezeShare",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "title",
        "type": "uint256"
      }
    ],
    "name": "getBook",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getCompInfo",
    "outputs": [
      {
        "components": [
          {
            "internalType": "uint40",
            "name": "regNum",
            "type": "uint40"
          },
          {
            "internalType": "uint48",
            "name": "regDate",
            "type": "uint48"
          },
          {
            "internalType": "uint8",
            "name": "typeOfEntity",
            "type": "uint8"
          },
          {
            "internalType": "uint8",
            "name": "currency",
            "type": "uint8"
          },
          {
            "internalType": "uint8",
            "name": "state",
            "type": "uint8"
          },
          {
            "internalType": "bytes18",
            "name": "symbol",
            "type": "bytes18"
          },
          {
            "internalType": "string",
            "name": "name",
            "type": "string"
          }
        ],
        "internalType": "struct IBaseKeeper.CompInfo",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getCompUser",
    "outputs": [
      {
        "components": [
          {
            "components": [
              {
                "internalType": "address",
                "name": "pubKey",
                "type": "address"
              },
              {
                "internalType": "uint16",
                "name": "discount",
                "type": "uint16"
              },
              {
                "internalType": "uint40",
                "name": "gift",
                "type": "uint40"
              },
              {
                "internalType": "uint40",
                "name": "coupon",
                "type": "uint40"
              }
            ],
            "internalType": "struct UsersRepo.Key",
            "name": "primeKey",
            "type": "tuple"
          },
          {
            "components": [
              {
                "internalType": "address",
                "name": "pubKey",
                "type": "address"
              },
              {
                "internalType": "uint16",
                "name": "discount",
                "type": "uint16"
              },
              {
                "internalType": "uint40",
                "name": "gift",
                "type": "uint40"
              },
              {
                "internalType": "uint40",
                "name": "coupon",
                "type": "uint40"
              }
            ],
            "internalType": "struct UsersRepo.Key",
            "name": "backupKey",
            "type": "tuple"
          }
        ],
        "internalType": "struct UsersRepo.User",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getDK",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "title",
        "type": "uint256"
      }
    ],
    "name": "getKeeper",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getOwner",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getRegCenter",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "keeper",
        "type": "address"
      }
    ],
    "name": "getTitleOfKeeper",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "owner",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "regCenter",
        "type": "address"
      }
    ],
    "name": "init",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "class",
        "type": "uint256"
      }
    ],
    "name": "initClass",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "dk",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "gk",
        "type": "address"
      }
    ],
    "name": "initKeepers",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "caller",
        "type": "address"
      }
    ],
    "name": "isKeeper",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "ia",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "seqOfDeal",
        "type": "uint256"
      }
    ],
    "name": "issueNewShare",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfShare",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "seqOfPld",
        "type": "uint256"
      },
      {
        "internalType": "bytes32",
        "name": "hashLock",
        "type": "bytes32"
      }
    ],
    "name": "lockPledge",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfPos",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "candidate",
        "type": "uint256"
      }
    ],
    "name": "nominateDirector",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfPos",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "candidate",
        "type": "uint256"
      }
    ],
    "name": "nominateOfficer",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfLR",
        "type": "uint256"
      }
    ],
    "name": "pause",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "components": [
          {
            "internalType": "address",
            "name": "from",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "to",
            "type": "address"
          },
          {
            "internalType": "uint256",
            "name": "value",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "validAfter",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "validBefore",
            "type": "uint256"
          },
          {
            "internalType": "bytes32",
            "name": "nonce",
            "type": "bytes32"
          },
          {
            "internalType": "uint8",
            "name": "v",
            "type": "uint8"
          },
          {
            "internalType": "bytes32",
            "name": "r",
            "type": "bytes32"
          },
          {
            "internalType": "bytes32",
            "name": "s",
            "type": "bytes32"
          }
        ],
        "internalType": "struct ICashier.TransferAuth",
        "name": "auth",
        "type": "tuple"
      },
      {
        "internalType": "uint256",
        "name": "seqOfShare",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "paid",
        "type": "uint256"
      }
    ],
    "name": "payInCapital",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "components": [
          {
            "internalType": "address",
            "name": "from",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "to",
            "type": "address"
          },
          {
            "internalType": "uint256",
            "name": "value",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "validAfter",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "validBefore",
            "type": "uint256"
          },
          {
            "internalType": "bytes32",
            "name": "nonce",
            "type": "bytes32"
          },
          {
            "internalType": "uint8",
            "name": "v",
            "type": "uint8"
          },
          {
            "internalType": "bytes32",
            "name": "r",
            "type": "bytes32"
          },
          {
            "internalType": "bytes32",
            "name": "s",
            "type": "bytes32"
          }
        ],
        "internalType": "struct ICashier.TransferAuth",
        "name": "auth",
        "type": "tuple"
      },
      {
        "internalType": "address",
        "name": "ia",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "seqOfDeal",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      }
    ],
    "name": "payOffApprovedDeal",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "doc",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "seqOfVR",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "executor",
        "type": "uint256"
      }
    ],
    "name": "proposeDocOfGM",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfMotion",
        "type": "uint256"
      }
    ],
    "name": "proposeMotionToBoard",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfMotion",
        "type": "uint256"
      }
    ],
    "name": "proposeMotionToGeneralMeeting",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address payable",
        "name": "receiver",
        "type": "address"
      }
    ],
    "name": "proposeToDeprecateGK",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "amt",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "expireDate",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "seqOfVR",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "seqOfDR",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "fundManager",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "executor",
        "type": "uint256"
      }
    ],
    "name": "proposeToDistributeUsd",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bool",
        "name": "toBMM",
        "type": "bool"
      },
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "internalType": "bool",
        "name": "isCBP",
        "type": "bool"
      },
      {
        "internalType": "uint256",
        "name": "amt",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "expireDate",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "seqOfVR",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "executor",
        "type": "uint256"
      }
    ],
    "name": "proposeToTransferFund",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "ia",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "seqOfDeal",
        "type": "uint256"
      },
      {
        "internalType": "bytes32",
        "name": "hashLock",
        "type": "bytes32"
      },
      {
        "internalType": "uint256",
        "name": "closingDeadline",
        "type": "uint256"
      }
    ],
    "name": "pushToCoffer",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfPos",
        "type": "uint256"
      }
    ],
    "name": "quitPosition",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfShare",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "seqOfPld",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "amt",
        "type": "uint256"
      }
    ],
    "name": "refundDebt",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "title",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "book",
        "type": "address"
      }
    ],
    "name": "regBook",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "bKey",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "groupRep",
        "type": "uint256"
      },
      {
        "internalType": "bytes32",
        "name": "idHash",
        "type": "bytes32"
      }
    ],
    "name": "regInvestor",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "title",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "keeper",
        "type": "address"
      }
    ],
    "name": "regKeeper",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfShare",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "seqOfPld",
        "type": "uint256"
      },
      {
        "internalType": "string",
        "name": "hashKey",
        "type": "string"
      }
    ],
    "name": "releasePledge",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfMotion",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "seqOfPos",
        "type": "uint256"
      }
    ],
    "name": "removeDirector",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfMotion",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "seqOfPos",
        "type": "uint256"
      }
    ],
    "name": "removeOfficer",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "hashLock",
        "type": "bytes32"
      },
      {
        "internalType": "string",
        "name": "hashKey",
        "type": "string"
      }
    ],
    "name": "requestPaidInCapital",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "userNo",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "seqOfLR",
        "type": "uint256"
      }
    ],
    "name": "revokeInvestor",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfShare",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "seqOfPld",
        "type": "uint256"
      }
    ],
    "name": "revokePledge",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint8",
        "name": "_currency",
        "type": "uint8"
      },
      {
        "internalType": "bytes18",
        "name": "_symbol",
        "type": "bytes18"
      },
      {
        "internalType": "string",
        "name": "_name",
        "type": "string"
      }
    ],
    "name": "setCompInfo",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "acct",
        "type": "address"
      }
    ],
    "name": "setDirectKeeper",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "max",
        "type": "uint256"
      }
    ],
    "name": "setMaxQtyOfMembers",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "gk",
        "type": "address"
      }
    ],
    "name": "setNewGK",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "acct",
        "type": "address"
      }
    ],
    "name": "setNewOwner",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfShare",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "amt",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "expireDate",
        "type": "uint256"
      },
      {
        "internalType": "bytes32",
        "name": "hashLock",
        "type": "bytes32"
      }
    ],
    "name": "setPayInAmt",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "ia",
        "type": "address"
      },
      {
        "internalType": "bytes32",
        "name": "sigHash",
        "type": "bytes32"
      }
    ],
    "name": "signIA",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "sha",
        "type": "address"
      },
      {
        "internalType": "bytes32",
        "name": "sigHash",
        "type": "bytes32"
      }
    ],
    "name": "signSHA",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "target",
        "type": "address"
      }
    ],
    "name": "takeBackKeys",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfMotion",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "seqOfPos",
        "type": "uint256"
      }
    ],
    "name": "takePosition",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfMotion",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "seqOfPos",
        "type": "uint256"
      }
    ],
    "name": "takeSeat",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "ia",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "seqOfDeal",
        "type": "uint256"
      }
    ],
    "name": "terminateDeal",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bool",
        "name": "fromBMM",
        "type": "bool"
      },
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "internalType": "bool",
        "name": "isCBP",
        "type": "bool"
      },
      {
        "internalType": "uint256",
        "name": "amt",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "expireDate",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "seqOfMotion",
        "type": "uint256"
      }
    ],
    "name": "transferFund",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfShare",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "seqOfPld",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "buyer",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "amt",
        "type": "uint256"
      }
    ],
    "name": "transferPledge",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "ia",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "seqOfDeal",
        "type": "uint256"
      }
    ],
    "name": "transferTargetShare",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfLR",
        "type": "uint256"
      }
    ],
    "name": "unPause",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfLR",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "seqOfShare",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "paid",
        "type": "uint256"
      },
      {
        "internalType": "bytes32",
        "name": "hashOrder",
        "type": "bytes32"
      }
    ],
    "name": "unfreezeShare",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfMotion",
        "type": "uint256"
      }
    ],
    "name": "voteCounting",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfMotion",
        "type": "uint256"
      }
    ],
    "name": "voteCountingOfGM",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "hashLock",
        "type": "bytes32"
      },
      {
        "internalType": "uint256",
        "name": "seqOfShare",
        "type": "uint256"
      }
    ],
    "name": "withdrawPayInAmt",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "stateMutability": "payable",
    "type": "receive"
  }
] as const;

  export class CoreKeeper__factory {
    static readonly abi = _abi;
    static createInterface(): CoreKeeperInterface {
      return new Interface(_abi) as CoreKeeperInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): CoreKeeper {
      return new Contract(address, _abi, runner) as unknown as CoreKeeper;
    }
  }
  