/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IROOKs, IROOKsInterface } from "../../../comps/modules/IROOKs.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfOpt",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "seqOfTarget",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "paidOfTarget",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "seqOfPledge",
        "type": "uint256"
      }
    ],
    "name": "createSwap",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfOpt",
        "type": "uint256"
      }
    ],
    "name": "execOption",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "components": [
          {
            "internalType": "address",
            "name": "from",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "to",
            "type": "address"
          },
          {
            "internalType": "uint256",
            "name": "value",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "validAfter",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "validBefore",
            "type": "uint256"
          },
          {
            "internalType": "bytes32",
            "name": "nonce",
            "type": "bytes32"
          },
          {
            "internalType": "uint8",
            "name": "v",
            "type": "uint8"
          },
          {
            "internalType": "bytes32",
            "name": "r",
            "type": "bytes32"
          },
          {
            "internalType": "bytes32",
            "name": "s",
            "type": "bytes32"
          }
        ],
        "internalType": "struct ICashier.TransferAuth",
        "name": "auth",
        "type": "tuple"
      },
      {
        "internalType": "address",
        "name": "ia",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "seqOfDeal",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "seqOfSwap",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      }
    ],
    "name": "payOffRejectedDeal",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "components": [
          {
            "internalType": "address",
            "name": "from",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "to",
            "type": "address"
          },
          {
            "internalType": "uint256",
            "name": "value",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "validAfter",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "validBefore",
            "type": "uint256"
          },
          {
            "internalType": "bytes32",
            "name": "nonce",
            "type": "bytes32"
          },
          {
            "internalType": "uint8",
            "name": "v",
            "type": "uint8"
          },
          {
            "internalType": "bytes32",
            "name": "r",
            "type": "bytes32"
          },
          {
            "internalType": "bytes32",
            "name": "s",
            "type": "bytes32"
          }
        ],
        "internalType": "struct ICashier.TransferAuth",
        "name": "auth",
        "type": "tuple"
      },
      {
        "internalType": "uint256",
        "name": "seqOfOpt",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "seqOfSwap",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      }
    ],
    "name": "payOffSwap",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "ia",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "seqOfDeal",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "seqOfSwap",
        "type": "uint256"
      }
    ],
    "name": "pickupPledgedShare",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "ia",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "seqOfDeal",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "paidOfTarget",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "seqOfPledge",
        "type": "uint256"
      }
    ],
    "name": "requestToBuy",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfOpt",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "seqOfSwap",
        "type": "uint256"
      }
    ],
    "name": "terminateSwap",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfOpt",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "d1",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "d2",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "d3",
        "type": "uint256"
      }
    ],
    "name": "updateOracle",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IROOKs__factory {
    static readonly abi = _abi;
    static createInterface(): IROOKsInterface {
      return new Interface(_abi) as IROOKsInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IROOKs {
      return new Contract(address, _abi, runner) as unknown as IROOKs;
    }
  }
  