/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { ICreateNewComp, ICreateNewCompInterface } from "../../comps/ICreateNewComp.js";

  const _abi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "bank",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "owner",
        "type": "address"
      }
    ],
    "name": "UpdateBank",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "typeOfDoc",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "seqOfDoc",
        "type": "uint256"
      }
    ],
    "name": "UpdateDocs4Book",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "typeOfDoc",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "seqOfDoc",
        "type": "uint256"
      }
    ],
    "name": "UpdateDocs4FundKeeper",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "typeOfEntity",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "seqOfDoc",
        "type": "uint256"
      }
    ],
    "name": "UpdateDocs4GK",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "typeOfDoc",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "seqOfDoc",
        "type": "uint256"
      }
    ],
    "name": "UpdateDocs4Keeper",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "typeOfEntity",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "dk",
        "type": "address"
      }
    ],
    "name": "createComp",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "typeOfDoc",
        "type": "uint256"
      }
    ],
    "name": "getSeqOfDoc4Book",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "typeOfDoc",
        "type": "uint256"
      }
    ],
    "name": "getSeqOfDoc4FundKeeper",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "typeOfEntity",
        "type": "uint256"
      }
    ],
    "name": "getSeqOfDoc4GK",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "typeOfDoc",
        "type": "uint256"
      }
    ],
    "name": "getSeqOfDoc4Keeper",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_bank",
        "type": "address"
      }
    ],
    "name": "updateBank",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "typeOfDoc",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "seqOfDoc",
        "type": "uint256"
      }
    ],
    "name": "updateDocs4Book",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "typeOfDoc",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "seqOfDoc",
        "type": "uint256"
      }
    ],
    "name": "updateDocs4FundKeeper",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "typeOfEntity",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "seqOfDoc",
        "type": "uint256"
      }
    ],
    "name": "updateDocs4GK",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "typeOfDoc",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "seqOfDoc",
        "type": "uint256"
      }
    ],
    "name": "updateDocs4Keeper",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class ICreateNewComp__factory {
    static readonly abi = _abi;
    static createInterface(): ICreateNewCompInterface {
      return new Interface(_abi) as ICreateNewCompInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): ICreateNewComp {
      return new Contract(address, _abi, runner) as unknown as ICreateNewComp;
    }
  }
  