/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IRegisterOfShares } from './IRegisterOfShares.js';
export type { RegisterOfShares } from './RegisterOfShares.js';