/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../../../common.js"
  
export declare namespace GoldChain {
      
    export type NodeStruct = {prev: BigNumberish, next: BigNumberish, issuer: BigNumberish, paid: BigNumberish, price: BigNumberish, expireDate: BigNumberish, isOffer: boolean}

    export type NodeStructOutput = [prev: bigint, next: bigint, issuer: bigint, paid: bigint, price: bigint, expireDate: bigint, isOffer: boolean] & {prev: bigint, next: bigint, issuer: bigint, paid: bigint, price: bigint, expireDate: bigint, isOffer: boolean }
  

    export type DataStruct = {classOfShare: BigNumberish, seqOfShare: BigNumberish, groupRep: BigNumberish, votingWeight: BigNumberish, distrWeight: BigNumberish, margin: BigNumberish, inEth: boolean, pubKey: AddressLike, date: BigNumberish, issueDate: BigNumberish}

    export type DataStructOutput = [classOfShare: bigint, seqOfShare: bigint, groupRep: bigint, votingWeight: bigint, distrWeight: bigint, margin: bigint, inEth: boolean, pubKey: string, date: bigint, issueDate: bigint] & {classOfShare: bigint, seqOfShare: bigint, groupRep: bigint, votingWeight: bigint, distrWeight: bigint, margin: bigint, inEth: boolean, pubKey: string, date: bigint, issueDate: bigint }
  

    export type OrderStruct = {node: GoldChain.NodeStruct, data: GoldChain.DataStruct}

    export type OrderStructOutput = [node: GoldChain.NodeStructOutput, data: GoldChain.DataStructOutput] & {node: GoldChain.NodeStructOutput, data: GoldChain.DataStructOutput }
  
    }

export declare namespace UsdOrdersRepo {
      
    export type DealStruct = {from: AddressLike, buyer: BigNumberish, groupRep: BigNumberish, classOfShare: BigNumberish, to: AddressLike, seller: BigNumberish, seqOfShare: BigNumberish, state: BigNumberish, inEth: boolean, isOffer: boolean, paid: BigNumberish, price: BigNumberish, votingWeight: BigNumberish, distrWeight: BigNumberish, consideration: BigNumberish}

    export type DealStructOutput = [from: string, buyer: bigint, groupRep: bigint, classOfShare: bigint, to: string, seller: bigint, seqOfShare: bigint, state: bigint, inEth: boolean, isOffer: boolean, paid: bigint, price: bigint, votingWeight: bigint, distrWeight: bigint, consideration: bigint] & {from: string, buyer: bigint, groupRep: bigint, classOfShare: bigint, to: string, seller: bigint, seqOfShare: bigint, state: bigint, inEth: boolean, isOffer: boolean, paid: bigint, price: bigint, votingWeight: bigint, distrWeight: bigint, consideration: bigint }
  
    }

  export interface ListOfOrdersInterface extends Interface {
    getFunction(nameOrSignature: "counterOfOrders" | "getClassesList" | "getDK" | "getOrder" | "getOrders" | "getOwner" | "getRegCenter" | "getSeqList" | "headOfList" | "init" | "initKeepers" | "isClass" | "isOrder" | "lengthOfList" | "placeBuyOrder" | "placeSellOrder" | "setDirectKeeper" | "setNewGK" | "setNewOwner" | "tailOfList" | "takeBackKeys" | "withdrawOrder"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DealClosed" | "OrderExpired" | "OrderPlaced" | "OrderWithdrawn" | "SetDirectKeeper" | "SetNewGK" | "SetNewOwner"): EventFragment;

    encodeFunctionData(functionFragment: 'counterOfOrders', values: [BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'getClassesList', values?: undefined): string;
encodeFunctionData(functionFragment: 'getDK', values?: undefined): string;
encodeFunctionData(functionFragment: 'getOrder', values: [BigNumberish, BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'getOrders', values: [BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'getOwner', values?: undefined): string;
encodeFunctionData(functionFragment: 'getRegCenter', values?: undefined): string;
encodeFunctionData(functionFragment: 'getSeqList', values: [BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'headOfList', values: [BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'init', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'initKeepers', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'isClass', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'isOrder', values: [BigNumberish, BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'lengthOfList', values: [BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'placeBuyOrder', values: [UsdOrdersRepo.DealStruct, BigNumberish]): string;
encodeFunctionData(functionFragment: 'placeSellOrder', values: [UsdOrdersRepo.DealStruct, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setDirectKeeper', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setNewGK', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setNewOwner', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'tailOfList', values: [BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'takeBackKeys', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'withdrawOrder', values: [BigNumberish, BigNumberish, boolean]): string;

    decodeFunctionResult(functionFragment: 'counterOfOrders', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getClassesList', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDK', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOrder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOrders', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRegCenter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSeqList', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'headOfList', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'init', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initKeepers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isClass', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isOrder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lengthOfList', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'placeBuyOrder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'placeSellOrder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setDirectKeeper', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setNewGK', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setNewOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tailOfList', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'takeBackKeys', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawOrder', data: BytesLike): Result;
  }

  
    export namespace DealClosedEvent {
      export type InputTuple = [fromSn: BytesLike, toSn: BytesLike, qtySn: BytesLike, consideration: BigNumberish];
      export type OutputTuple = [fromSn: string, toSn: string, qtySn: string, consideration: bigint];
      export interface OutputObject {fromSn: string, toSn: string, qtySn: string, consideration: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OrderExpiredEvent {
      export type InputTuple = [head: BytesLike, body: BytesLike, isOffer: boolean];
      export type OutputTuple = [head: string, body: string, isOffer: boolean];
      export interface OutputObject {head: string, body: string, isOffer: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OrderPlacedEvent {
      export type InputTuple = [fromSn: BytesLike, toSn: BytesLike, qtySn: BytesLike, isOffer: boolean];
      export type OutputTuple = [fromSn: string, toSn: string, qtySn: string, isOffer: boolean];
      export interface OutputObject {fromSn: string, toSn: string, qtySn: string, isOffer: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OrderWithdrawnEvent {
      export type InputTuple = [head: BytesLike, body: BytesLike, isOffer: boolean];
      export type OutputTuple = [head: string, body: string, isOffer: boolean];
      export interface OutputObject {head: string, body: string, isOffer: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SetDirectKeeperEvent {
      export type InputTuple = [keeper: AddressLike];
      export type OutputTuple = [keeper: string];
      export interface OutputObject {keeper: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SetNewGKEvent {
      export type InputTuple = [gk: AddressLike];
      export type OutputTuple = [gk: string];
      export interface OutputObject {gk: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SetNewOwnerEvent {
      export type InputTuple = [owner: AddressLike];
      export type OutputTuple = [owner: string];
      export interface OutputObject {owner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ListOfOrders extends BaseContract {
    
    connect(runner?: ContractRunner | null): ListOfOrders;
    waitForDeployment(): Promise<this>;

    interface: ListOfOrdersInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    counterOfOrders: TypedContractMethod<
      [classOfShare: BigNumberish, isOffer: boolean, ],
      [bigint],
      'view'
    >
    

    
    getClassesList: TypedContractMethod<
      [],
      [bigint[]],
      'view'
    >
    

    
    getDK: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getOrder: TypedContractMethod<
      [classOfShare: BigNumberish, seqOfOrder: BigNumberish, isOffer: boolean, ],
      [GoldChain.OrderStructOutput],
      'view'
    >
    

    
    getOrders: TypedContractMethod<
      [classOfShare: BigNumberish, isOffer: boolean, ],
      [GoldChain.OrderStructOutput[]],
      'view'
    >
    

    
    getOwner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getRegCenter: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getSeqList: TypedContractMethod<
      [classOfShare: BigNumberish, isOffer: boolean, ],
      [bigint[]],
      'view'
    >
    

    
    headOfList: TypedContractMethod<
      [classOfShare: BigNumberish, isOffer: boolean, ],
      [bigint],
      'view'
    >
    

    
    init: TypedContractMethod<
      [owner: AddressLike, regCenter: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    initKeepers: TypedContractMethod<
      [dk: AddressLike, gk: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    isClass: TypedContractMethod<
      [classOfShare: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    isOrder: TypedContractMethod<
      [classOfShare: BigNumberish, seqOfOrder: BigNumberish, isOffer: boolean, ],
      [boolean],
      'view'
    >
    

    
    lengthOfList: TypedContractMethod<
      [classOfShare: BigNumberish, isOffer: boolean, ],
      [bigint],
      'view'
    >
    

    
    placeBuyOrder: TypedContractMethod<
      [input: UsdOrdersRepo.DealStruct, execHours: BigNumberish, ],
      [[UsdOrdersRepo.DealStructOutput[], bigint, GoldChain.OrderStructOutput[], bigint, UsdOrdersRepo.DealStructOutput] & {deals: UsdOrdersRepo.DealStructOutput[], lenOfDeals: bigint, expired: GoldChain.OrderStructOutput[], lenOfExpired: bigint, bid: UsdOrdersRepo.DealStructOutput }],
      'nonpayable'
    >
    

    
    placeSellOrder: TypedContractMethod<
      [input: UsdOrdersRepo.DealStruct, execHours: BigNumberish, ],
      [[UsdOrdersRepo.DealStructOutput[], bigint, GoldChain.OrderStructOutput[], bigint, UsdOrdersRepo.DealStructOutput] & {deals: UsdOrdersRepo.DealStructOutput[], lenOfDeals: bigint, expired: GoldChain.OrderStructOutput[], lenOfExpired: bigint, offer: UsdOrdersRepo.DealStructOutput }],
      'nonpayable'
    >
    

    
    setDirectKeeper: TypedContractMethod<
      [acct: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setNewGK: TypedContractMethod<
      [gk: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setNewOwner: TypedContractMethod<
      [acct: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    tailOfList: TypedContractMethod<
      [classOfShare: BigNumberish, isOffer: boolean, ],
      [bigint],
      'view'
    >
    

    
    takeBackKeys: TypedContractMethod<
      [target: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    withdrawOrder: TypedContractMethod<
      [classOfShare: BigNumberish, seqOfOrder: BigNumberish, isOffer: boolean, ],
      [GoldChain.OrderStructOutput],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'counterOfOrders'): TypedContractMethod<
      [classOfShare: BigNumberish, isOffer: boolean, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getClassesList'): TypedContractMethod<
      [],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getDK'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getOrder'): TypedContractMethod<
      [classOfShare: BigNumberish, seqOfOrder: BigNumberish, isOffer: boolean, ],
      [GoldChain.OrderStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getOrders'): TypedContractMethod<
      [classOfShare: BigNumberish, isOffer: boolean, ],
      [GoldChain.OrderStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getOwner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getRegCenter'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getSeqList'): TypedContractMethod<
      [classOfShare: BigNumberish, isOffer: boolean, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'headOfList'): TypedContractMethod<
      [classOfShare: BigNumberish, isOffer: boolean, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'init'): TypedContractMethod<
      [owner: AddressLike, regCenter: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'initKeepers'): TypedContractMethod<
      [dk: AddressLike, gk: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'isClass'): TypedContractMethod<
      [classOfShare: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isOrder'): TypedContractMethod<
      [classOfShare: BigNumberish, seqOfOrder: BigNumberish, isOffer: boolean, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'lengthOfList'): TypedContractMethod<
      [classOfShare: BigNumberish, isOffer: boolean, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'placeBuyOrder'): TypedContractMethod<
      [input: UsdOrdersRepo.DealStruct, execHours: BigNumberish, ],
      [[UsdOrdersRepo.DealStructOutput[], bigint, GoldChain.OrderStructOutput[], bigint, UsdOrdersRepo.DealStructOutput] & {deals: UsdOrdersRepo.DealStructOutput[], lenOfDeals: bigint, expired: GoldChain.OrderStructOutput[], lenOfExpired: bigint, bid: UsdOrdersRepo.DealStructOutput }],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'placeSellOrder'): TypedContractMethod<
      [input: UsdOrdersRepo.DealStruct, execHours: BigNumberish, ],
      [[UsdOrdersRepo.DealStructOutput[], bigint, GoldChain.OrderStructOutput[], bigint, UsdOrdersRepo.DealStructOutput] & {deals: UsdOrdersRepo.DealStructOutput[], lenOfDeals: bigint, expired: GoldChain.OrderStructOutput[], lenOfExpired: bigint, offer: UsdOrdersRepo.DealStructOutput }],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setDirectKeeper'): TypedContractMethod<
      [acct: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setNewGK'): TypedContractMethod<
      [gk: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setNewOwner'): TypedContractMethod<
      [acct: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'tailOfList'): TypedContractMethod<
      [classOfShare: BigNumberish, isOffer: boolean, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'takeBackKeys'): TypedContractMethod<
      [target: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawOrder'): TypedContractMethod<
      [classOfShare: BigNumberish, seqOfOrder: BigNumberish, isOffer: boolean, ],
      [GoldChain.OrderStructOutput],
      'nonpayable'
    >;

    getEvent(key: 'DealClosed'): TypedContractEvent<DealClosedEvent.InputTuple, DealClosedEvent.OutputTuple, DealClosedEvent.OutputObject>;
getEvent(key: 'OrderExpired'): TypedContractEvent<OrderExpiredEvent.InputTuple, OrderExpiredEvent.OutputTuple, OrderExpiredEvent.OutputObject>;
getEvent(key: 'OrderPlaced'): TypedContractEvent<OrderPlacedEvent.InputTuple, OrderPlacedEvent.OutputTuple, OrderPlacedEvent.OutputObject>;
getEvent(key: 'OrderWithdrawn'): TypedContractEvent<OrderWithdrawnEvent.InputTuple, OrderWithdrawnEvent.OutputTuple, OrderWithdrawnEvent.OutputObject>;
getEvent(key: 'SetDirectKeeper'): TypedContractEvent<SetDirectKeeperEvent.InputTuple, SetDirectKeeperEvent.OutputTuple, SetDirectKeeperEvent.OutputObject>;
getEvent(key: 'SetNewGK'): TypedContractEvent<SetNewGKEvent.InputTuple, SetNewGKEvent.OutputTuple, SetNewGKEvent.OutputObject>;
getEvent(key: 'SetNewOwner'): TypedContractEvent<SetNewOwnerEvent.InputTuple, SetNewOwnerEvent.OutputTuple, SetNewOwnerEvent.OutputObject>;

    filters: {
      
      'DealClosed(bytes32,bytes32,bytes32,uint256)': TypedContractEvent<DealClosedEvent.InputTuple, DealClosedEvent.OutputTuple, DealClosedEvent.OutputObject>;
      DealClosed: TypedContractEvent<DealClosedEvent.InputTuple, DealClosedEvent.OutputTuple, DealClosedEvent.OutputObject>;
    

      'OrderExpired(bytes32,bytes32,bool)': TypedContractEvent<OrderExpiredEvent.InputTuple, OrderExpiredEvent.OutputTuple, OrderExpiredEvent.OutputObject>;
      OrderExpired: TypedContractEvent<OrderExpiredEvent.InputTuple, OrderExpiredEvent.OutputTuple, OrderExpiredEvent.OutputObject>;
    

      'OrderPlaced(bytes32,bytes32,bytes32,bool)': TypedContractEvent<OrderPlacedEvent.InputTuple, OrderPlacedEvent.OutputTuple, OrderPlacedEvent.OutputObject>;
      OrderPlaced: TypedContractEvent<OrderPlacedEvent.InputTuple, OrderPlacedEvent.OutputTuple, OrderPlacedEvent.OutputObject>;
    

      'OrderWithdrawn(bytes32,bytes32,bool)': TypedContractEvent<OrderWithdrawnEvent.InputTuple, OrderWithdrawnEvent.OutputTuple, OrderWithdrawnEvent.OutputObject>;
      OrderWithdrawn: TypedContractEvent<OrderWithdrawnEvent.InputTuple, OrderWithdrawnEvent.OutputTuple, OrderWithdrawnEvent.OutputObject>;
    

      'SetDirectKeeper(address)': TypedContractEvent<SetDirectKeeperEvent.InputTuple, SetDirectKeeperEvent.OutputTuple, SetDirectKeeperEvent.OutputObject>;
      SetDirectKeeper: TypedContractEvent<SetDirectKeeperEvent.InputTuple, SetDirectKeeperEvent.OutputTuple, SetDirectKeeperEvent.OutputObject>;
    

      'SetNewGK(address)': TypedContractEvent<SetNewGKEvent.InputTuple, SetNewGKEvent.OutputTuple, SetNewGKEvent.OutputObject>;
      SetNewGK: TypedContractEvent<SetNewGKEvent.InputTuple, SetNewGKEvent.OutputTuple, SetNewGKEvent.OutputObject>;
    

      'SetNewOwner(address)': TypedContractEvent<SetNewOwnerEvent.InputTuple, SetNewOwnerEvent.OutputTuple, SetNewOwnerEvent.OutputObject>;
      SetNewOwner: TypedContractEvent<SetNewOwnerEvent.InputTuple, SetNewOwnerEvent.OutputTuple, SetNewOwnerEvent.OutputObject>;
    
    };
  }