/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface GMMKeeperInterface extends Interface {
    getFunction(nameOrSignature: "castVoteOfGM" | "createActionOfGM" | "createMotionToRemoveDirector" | "deprecateGK" | "entrustDelegaterForGeneralMeeting" | "execActionOfGM" | "getDK" | "getOwner" | "getRegCenter" | "init" | "initKeepers" | "nominateDirector" | "proposeDocOfGM" | "proposeMotionToGeneralMeeting" | "proposeToDeprecateGK" | "proposeToDistributeUsd" | "proposeToTransferFund" | "setDirectKeeper" | "setNewGK" | "setNewOwner" | "takeBackKeys" | "voteCountingOfGM"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ChargeRoyalty" | "ExecAction" | "SetDirectKeeper" | "SetNewGK" | "SetNewOwner"): EventFragment;

    encodeFunctionData(functionFragment: 'castVoteOfGM', values: [BigNumberish, BigNumberish, BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'createActionOfGM', values: [BigNumberish, AddressLike[], BigNumberish[], BytesLike[], BytesLike, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'createMotionToRemoveDirector', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'deprecateGK', values: [AddressLike, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'entrustDelegaterForGeneralMeeting', values: [BigNumberish, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'execActionOfGM', values: [BigNumberish, AddressLike[], BigNumberish[], BytesLike[], BytesLike, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'getDK', values?: undefined): string;
encodeFunctionData(functionFragment: 'getOwner', values?: undefined): string;
encodeFunctionData(functionFragment: 'getRegCenter', values?: undefined): string;
encodeFunctionData(functionFragment: 'init', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'initKeepers', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'nominateDirector', values: [BigNumberish, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'proposeDocOfGM', values: [BigNumberish, BigNumberish, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'proposeMotionToGeneralMeeting', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'proposeToDeprecateGK', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'proposeToDistributeUsd', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'proposeToTransferFund', values: [AddressLike, boolean, BigNumberish, BigNumberish, BigNumberish, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'setDirectKeeper', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setNewGK', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setNewOwner', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'takeBackKeys', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'voteCountingOfGM', values: [BigNumberish, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'castVoteOfGM', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createActionOfGM', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createMotionToRemoveDirector', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deprecateGK', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'entrustDelegaterForGeneralMeeting', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'execActionOfGM', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDK', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRegCenter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'init', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initKeepers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nominateDirector', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposeDocOfGM', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposeMotionToGeneralMeeting', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposeToDeprecateGK', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposeToDistributeUsd', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposeToTransferFund', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setDirectKeeper', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setNewGK', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setNewOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'takeBackKeys', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'voteCountingOfGM', data: BytesLike): Result;
  }

  
    export namespace ChargeRoyaltyEvent {
      export type InputTuple = [typeOfDoc: BigNumberish, version: BigNumberish, rate: BigNumberish, user: BigNumberish, author: BigNumberish];
      export type OutputTuple = [typeOfDoc: bigint, version: bigint, rate: bigint, user: bigint, author: bigint];
      export interface OutputObject {typeOfDoc: bigint, version: bigint, rate: bigint, user: bigint, author: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ExecActionEvent {
      export type InputTuple = [targets: AddressLike, values: BigNumberish, params: BytesLike, seqOfMotion: BigNumberish, caller: BigNumberish];
      export type OutputTuple = [targets: string, values: bigint, params: string, seqOfMotion: bigint, caller: bigint];
      export interface OutputObject {targets: string, values: bigint, params: string, seqOfMotion: bigint, caller: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SetDirectKeeperEvent {
      export type InputTuple = [keeper: AddressLike];
      export type OutputTuple = [keeper: string];
      export interface OutputObject {keeper: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SetNewGKEvent {
      export type InputTuple = [gk: AddressLike];
      export type OutputTuple = [gk: string];
      export interface OutputObject {gk: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SetNewOwnerEvent {
      export type InputTuple = [owner: AddressLike];
      export type OutputTuple = [owner: string];
      export interface OutputObject {owner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface GMMKeeper extends BaseContract {
    
    connect(runner?: ContractRunner | null): GMMKeeper;
    waitForDeployment(): Promise<this>;

    interface: GMMKeeperInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    castVoteOfGM: TypedContractMethod<
      [seqOfMotion: BigNumberish, attitude: BigNumberish, sigHash: BytesLike, msgSender: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    createActionOfGM: TypedContractMethod<
      [seqOfVR: BigNumberish, targets: AddressLike[], values: BigNumberish[], params: BytesLike[], desHash: BytesLike, executor: BigNumberish, msgSender: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    createMotionToRemoveDirector: TypedContractMethod<
      [seqOfPos: BigNumberish, msgSender: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    deprecateGK: TypedContractMethod<
      [receiver: AddressLike, seqOfMotion: BigNumberish, msgSender: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    entrustDelegaterForGeneralMeeting: TypedContractMethod<
      [seqOfMotion: BigNumberish, delegate: BigNumberish, msgSender: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    execActionOfGM: TypedContractMethod<
      [typeOfAction: BigNumberish, targets: AddressLike[], values: BigNumberish[], params: BytesLike[], desHash: BytesLike, seqOfMotion: BigNumberish, msgSender: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    getDK: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getOwner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getRegCenter: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    init: TypedContractMethod<
      [owner: AddressLike, regCenter: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    initKeepers: TypedContractMethod<
      [dk: AddressLike, gk: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    nominateDirector: TypedContractMethod<
      [seqOfPos: BigNumberish, candidate: BigNumberish, msgSender: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    proposeDocOfGM: TypedContractMethod<
      [doc: BigNumberish, seqOfVR: BigNumberish, executor: BigNumberish, msgSender: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    proposeMotionToGeneralMeeting: TypedContractMethod<
      [seqOfMotion: BigNumberish, msgSender: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    proposeToDeprecateGK: TypedContractMethod<
      [receiver: AddressLike, msgSender: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    proposeToDistributeUsd: TypedContractMethod<
      [amt: BigNumberish, expireDate: BigNumberish, seqOfVR: BigNumberish, seqOfDR: BigNumberish, para: BigNumberish, executor: BigNumberish, msgSender: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    proposeToTransferFund: TypedContractMethod<
      [to: AddressLike, isCBP: boolean, amt: BigNumberish, expireDate: BigNumberish, seqOfVR: BigNumberish, executor: BigNumberish, msgSender: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setDirectKeeper: TypedContractMethod<
      [acct: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setNewGK: TypedContractMethod<
      [gk: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setNewOwner: TypedContractMethod<
      [acct: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    takeBackKeys: TypedContractMethod<
      [target: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    voteCountingOfGM: TypedContractMethod<
      [seqOfMotion: BigNumberish, msgSender: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'castVoteOfGM'): TypedContractMethod<
      [seqOfMotion: BigNumberish, attitude: BigNumberish, sigHash: BytesLike, msgSender: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createActionOfGM'): TypedContractMethod<
      [seqOfVR: BigNumberish, targets: AddressLike[], values: BigNumberish[], params: BytesLike[], desHash: BytesLike, executor: BigNumberish, msgSender: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createMotionToRemoveDirector'): TypedContractMethod<
      [seqOfPos: BigNumberish, msgSender: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'deprecateGK'): TypedContractMethod<
      [receiver: AddressLike, seqOfMotion: BigNumberish, msgSender: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'entrustDelegaterForGeneralMeeting'): TypedContractMethod<
      [seqOfMotion: BigNumberish, delegate: BigNumberish, msgSender: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'execActionOfGM'): TypedContractMethod<
      [typeOfAction: BigNumberish, targets: AddressLike[], values: BigNumberish[], params: BytesLike[], desHash: BytesLike, seqOfMotion: BigNumberish, msgSender: AddressLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getDK'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getOwner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getRegCenter'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'init'): TypedContractMethod<
      [owner: AddressLike, regCenter: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'initKeepers'): TypedContractMethod<
      [dk: AddressLike, gk: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'nominateDirector'): TypedContractMethod<
      [seqOfPos: BigNumberish, candidate: BigNumberish, msgSender: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'proposeDocOfGM'): TypedContractMethod<
      [doc: BigNumberish, seqOfVR: BigNumberish, executor: BigNumberish, msgSender: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'proposeMotionToGeneralMeeting'): TypedContractMethod<
      [seqOfMotion: BigNumberish, msgSender: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'proposeToDeprecateGK'): TypedContractMethod<
      [receiver: AddressLike, msgSender: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'proposeToDistributeUsd'): TypedContractMethod<
      [amt: BigNumberish, expireDate: BigNumberish, seqOfVR: BigNumberish, seqOfDR: BigNumberish, para: BigNumberish, executor: BigNumberish, msgSender: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'proposeToTransferFund'): TypedContractMethod<
      [to: AddressLike, isCBP: boolean, amt: BigNumberish, expireDate: BigNumberish, seqOfVR: BigNumberish, executor: BigNumberish, msgSender: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setDirectKeeper'): TypedContractMethod<
      [acct: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setNewGK'): TypedContractMethod<
      [gk: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setNewOwner'): TypedContractMethod<
      [acct: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'takeBackKeys'): TypedContractMethod<
      [target: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'voteCountingOfGM'): TypedContractMethod<
      [seqOfMotion: BigNumberish, msgSender: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ChargeRoyalty'): TypedContractEvent<ChargeRoyaltyEvent.InputTuple, ChargeRoyaltyEvent.OutputTuple, ChargeRoyaltyEvent.OutputObject>;
getEvent(key: 'ExecAction'): TypedContractEvent<ExecActionEvent.InputTuple, ExecActionEvent.OutputTuple, ExecActionEvent.OutputObject>;
getEvent(key: 'SetDirectKeeper'): TypedContractEvent<SetDirectKeeperEvent.InputTuple, SetDirectKeeperEvent.OutputTuple, SetDirectKeeperEvent.OutputObject>;
getEvent(key: 'SetNewGK'): TypedContractEvent<SetNewGKEvent.InputTuple, SetNewGKEvent.OutputTuple, SetNewGKEvent.OutputObject>;
getEvent(key: 'SetNewOwner'): TypedContractEvent<SetNewOwnerEvent.InputTuple, SetNewOwnerEvent.OutputTuple, SetNewOwnerEvent.OutputObject>;

    filters: {
      
      'ChargeRoyalty(uint256,uint256,uint256,uint256,uint256)': TypedContractEvent<ChargeRoyaltyEvent.InputTuple, ChargeRoyaltyEvent.OutputTuple, ChargeRoyaltyEvent.OutputObject>;
      ChargeRoyalty: TypedContractEvent<ChargeRoyaltyEvent.InputTuple, ChargeRoyaltyEvent.OutputTuple, ChargeRoyaltyEvent.OutputObject>;
    

      'ExecAction(address,uint256,bytes,uint256,uint256)': TypedContractEvent<ExecActionEvent.InputTuple, ExecActionEvent.OutputTuple, ExecActionEvent.OutputObject>;
      ExecAction: TypedContractEvent<ExecActionEvent.InputTuple, ExecActionEvent.OutputTuple, ExecActionEvent.OutputObject>;
    

      'SetDirectKeeper(address)': TypedContractEvent<SetDirectKeeperEvent.InputTuple, SetDirectKeeperEvent.OutputTuple, SetDirectKeeperEvent.OutputObject>;
      SetDirectKeeper: TypedContractEvent<SetDirectKeeperEvent.InputTuple, SetDirectKeeperEvent.OutputTuple, SetDirectKeeperEvent.OutputObject>;
    

      'SetNewGK(address)': TypedContractEvent<SetNewGKEvent.InputTuple, SetNewGKEvent.OutputTuple, SetNewGKEvent.OutputObject>;
      SetNewGK: TypedContractEvent<SetNewGKEvent.InputTuple, SetNewGKEvent.OutputTuple, SetNewGKEvent.OutputObject>;
    

      'SetNewOwner(address)': TypedContractEvent<SetNewOwnerEvent.InputTuple, SetNewOwnerEvent.OutputTuple, SetNewOwnerEvent.OutputObject>;
      SetNewOwner: TypedContractEvent<SetNewOwnerEvent.InputTuple, SetNewOwnerEvent.OutputTuple, SetNewOwnerEvent.OutputObject>;
    
    };
  }