/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface IRODKeeperInterface extends Interface {
    getFunction(nameOrSignature: "quitPosition" | "removeDirector" | "removeOfficer" | "takePosition" | "takeSeat"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'quitPosition', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'removeDirector', values: [BigNumberish, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'removeOfficer', values: [BigNumberish, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'takePosition', values: [BigNumberish, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'takeSeat', values: [BigNumberish, BigNumberish, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'quitPosition', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeDirector', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeOfficer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'takePosition', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'takeSeat', data: BytesLike): Result;
  }

  

  export interface IRODKeeper extends BaseContract {
    
    connect(runner?: ContractRunner | null): IRODKeeper;
    waitForDeployment(): Promise<this>;

    interface: IRODKeeperInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    quitPosition: TypedContractMethod<
      [seqOfPos: BigNumberish, msgSender: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    removeDirector: TypedContractMethod<
      [seqOfMotion: BigNumberish, seqOfPos: BigNumberish, msgSender: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    removeOfficer: TypedContractMethod<
      [seqOfMotion: BigNumberish, seqOfPos: BigNumberish, msgSender: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    takePosition: TypedContractMethod<
      [seqOfMotion: BigNumberish, seqOfPos: BigNumberish, msgSender: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    takeSeat: TypedContractMethod<
      [seqOfMotion: BigNumberish, seqOfPos: BigNumberish, msgSender: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'quitPosition'): TypedContractMethod<
      [seqOfPos: BigNumberish, msgSender: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'removeDirector'): TypedContractMethod<
      [seqOfMotion: BigNumberish, seqOfPos: BigNumberish, msgSender: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'removeOfficer'): TypedContractMethod<
      [seqOfMotion: BigNumberish, seqOfPos: BigNumberish, msgSender: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'takePosition'): TypedContractMethod<
      [seqOfMotion: BigNumberish, seqOfPos: BigNumberish, msgSender: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'takeSeat'): TypedContractMethod<
      [seqOfMotion: BigNumberish, seqOfPos: BigNumberish, msgSender: AddressLike, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }