/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../../common.js"
  
export declare namespace ICashier {
      
    export type TransferAuthStruct = {from: AddressLike, to: AddressLike, value: BigNumberish, validAfter: BigNumberish, validBefore: BigNumberish, nonce: BytesLike, v: BigNumberish, r: BytesLike, s: BytesLike}

    export type TransferAuthStructOutput = [from: string, to: string, value: bigint, validAfter: bigint, validBefore: bigint, nonce: string, v: bigint, r: string, s: string] & {from: string, to: string, value: bigint, validAfter: bigint, validBefore: bigint, nonce: string, v: bigint, r: string, s: string }
  
    }

  export interface ROMKeeperInterface extends Interface {
    getFunction(nameOrSignature: "decreaseCapital" | "getDK" | "getOwner" | "getRegCenter" | "init" | "initKeepers" | "payInCapital" | "requestPaidInCapital" | "setDirectKeeper" | "setMaxQtyOfMembers" | "setNewGK" | "setNewOwner" | "setPayInAmt" | "takeBackKeys" | "updatePaidInDeadline" | "withdrawPayInAmt"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ChargeRoyalty" | "PayInCapital" | "SetDirectKeeper" | "SetNewGK" | "SetNewOwner"): EventFragment;

    encodeFunctionData(functionFragment: 'decreaseCapital', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getDK', values?: undefined): string;
encodeFunctionData(functionFragment: 'getOwner', values?: undefined): string;
encodeFunctionData(functionFragment: 'getRegCenter', values?: undefined): string;
encodeFunctionData(functionFragment: 'init', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'initKeepers', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'payInCapital', values: [ICashier.TransferAuthStruct, BigNumberish, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'requestPaidInCapital', values: [BytesLike, string]): string;
encodeFunctionData(functionFragment: 'setDirectKeeper', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setMaxQtyOfMembers', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setNewGK', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setNewOwner', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setPayInAmt', values: [BigNumberish, BigNumberish, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'takeBackKeys', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updatePaidInDeadline', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdrawPayInAmt', values: [BytesLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'decreaseCapital', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDK', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRegCenter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'init', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initKeepers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'payInCapital', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requestPaidInCapital', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setDirectKeeper', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMaxQtyOfMembers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setNewGK', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setNewOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPayInAmt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'takeBackKeys', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updatePaidInDeadline', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawPayInAmt', data: BytesLike): Result;
  }

  
    export namespace ChargeRoyaltyEvent {
      export type InputTuple = [typeOfDoc: BigNumberish, version: BigNumberish, rate: BigNumberish, user: BigNumberish, author: BigNumberish];
      export type OutputTuple = [typeOfDoc: bigint, version: bigint, rate: bigint, user: bigint, author: bigint];
      export interface OutputObject {typeOfDoc: bigint, version: bigint, rate: bigint, user: bigint, author: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PayInCapitalEvent {
      export type InputTuple = [seqOfShare: BigNumberish, amt: BigNumberish, valueOfDeal: BigNumberish];
      export type OutputTuple = [seqOfShare: bigint, amt: bigint, valueOfDeal: bigint];
      export interface OutputObject {seqOfShare: bigint, amt: bigint, valueOfDeal: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SetDirectKeeperEvent {
      export type InputTuple = [keeper: AddressLike];
      export type OutputTuple = [keeper: string];
      export interface OutputObject {keeper: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SetNewGKEvent {
      export type InputTuple = [gk: AddressLike];
      export type OutputTuple = [gk: string];
      export interface OutputObject {gk: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SetNewOwnerEvent {
      export type InputTuple = [owner: AddressLike];
      export type OutputTuple = [owner: string];
      export interface OutputObject {owner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ROMKeeper extends BaseContract {
    
    connect(runner?: ContractRunner | null): ROMKeeper;
    waitForDeployment(): Promise<this>;

    interface: ROMKeeperInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    decreaseCapital: TypedContractMethod<
      [seqOfShare: BigNumberish, paid: BigNumberish, par: BigNumberish, amt: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getDK: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getOwner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getRegCenter: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    init: TypedContractMethod<
      [owner: AddressLike, regCenter: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    initKeepers: TypedContractMethod<
      [dk: AddressLike, gk: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    payInCapital: TypedContractMethod<
      [auth: ICashier.TransferAuthStruct, seqOfShare: BigNumberish, paid: BigNumberish, msgSender: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    requestPaidInCapital: TypedContractMethod<
      [hashLock: BytesLike, hashKey: string, ],
      [void],
      'nonpayable'
    >
    

    
    setDirectKeeper: TypedContractMethod<
      [acct: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setMaxQtyOfMembers: TypedContractMethod<
      [max: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setNewGK: TypedContractMethod<
      [gk: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setNewOwner: TypedContractMethod<
      [acct: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setPayInAmt: TypedContractMethod<
      [seqOfShare: BigNumberish, amt: BigNumberish, expireDate: BigNumberish, hashLock: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    takeBackKeys: TypedContractMethod<
      [target: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updatePaidInDeadline: TypedContractMethod<
      [seqOfShare: BigNumberish, line: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    withdrawPayInAmt: TypedContractMethod<
      [hashLock: BytesLike, seqOfShare: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'decreaseCapital'): TypedContractMethod<
      [seqOfShare: BigNumberish, paid: BigNumberish, par: BigNumberish, amt: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getDK'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getOwner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getRegCenter'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'init'): TypedContractMethod<
      [owner: AddressLike, regCenter: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'initKeepers'): TypedContractMethod<
      [dk: AddressLike, gk: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'payInCapital'): TypedContractMethod<
      [auth: ICashier.TransferAuthStruct, seqOfShare: BigNumberish, paid: BigNumberish, msgSender: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'requestPaidInCapital'): TypedContractMethod<
      [hashLock: BytesLike, hashKey: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setDirectKeeper'): TypedContractMethod<
      [acct: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setMaxQtyOfMembers'): TypedContractMethod<
      [max: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setNewGK'): TypedContractMethod<
      [gk: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setNewOwner'): TypedContractMethod<
      [acct: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setPayInAmt'): TypedContractMethod<
      [seqOfShare: BigNumberish, amt: BigNumberish, expireDate: BigNumberish, hashLock: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'takeBackKeys'): TypedContractMethod<
      [target: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updatePaidInDeadline'): TypedContractMethod<
      [seqOfShare: BigNumberish, line: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawPayInAmt'): TypedContractMethod<
      [hashLock: BytesLike, seqOfShare: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ChargeRoyalty'): TypedContractEvent<ChargeRoyaltyEvent.InputTuple, ChargeRoyaltyEvent.OutputTuple, ChargeRoyaltyEvent.OutputObject>;
getEvent(key: 'PayInCapital'): TypedContractEvent<PayInCapitalEvent.InputTuple, PayInCapitalEvent.OutputTuple, PayInCapitalEvent.OutputObject>;
getEvent(key: 'SetDirectKeeper'): TypedContractEvent<SetDirectKeeperEvent.InputTuple, SetDirectKeeperEvent.OutputTuple, SetDirectKeeperEvent.OutputObject>;
getEvent(key: 'SetNewGK'): TypedContractEvent<SetNewGKEvent.InputTuple, SetNewGKEvent.OutputTuple, SetNewGKEvent.OutputObject>;
getEvent(key: 'SetNewOwner'): TypedContractEvent<SetNewOwnerEvent.InputTuple, SetNewOwnerEvent.OutputTuple, SetNewOwnerEvent.OutputObject>;

    filters: {
      
      'ChargeRoyalty(uint256,uint256,uint256,uint256,uint256)': TypedContractEvent<ChargeRoyaltyEvent.InputTuple, ChargeRoyaltyEvent.OutputTuple, ChargeRoyaltyEvent.OutputObject>;
      ChargeRoyalty: TypedContractEvent<ChargeRoyaltyEvent.InputTuple, ChargeRoyaltyEvent.OutputTuple, ChargeRoyaltyEvent.OutputObject>;
    

      'PayInCapital(uint256,uint256,uint256)': TypedContractEvent<PayInCapitalEvent.InputTuple, PayInCapitalEvent.OutputTuple, PayInCapitalEvent.OutputObject>;
      PayInCapital: TypedContractEvent<PayInCapitalEvent.InputTuple, PayInCapitalEvent.OutputTuple, PayInCapitalEvent.OutputObject>;
    

      'SetDirectKeeper(address)': TypedContractEvent<SetDirectKeeperEvent.InputTuple, SetDirectKeeperEvent.OutputTuple, SetDirectKeeperEvent.OutputObject>;
      SetDirectKeeper: TypedContractEvent<SetDirectKeeperEvent.InputTuple, SetDirectKeeperEvent.OutputTuple, SetDirectKeeperEvent.OutputObject>;
    

      'SetNewGK(address)': TypedContractEvent<SetNewGKEvent.InputTuple, SetNewGKEvent.OutputTuple, SetNewGKEvent.OutputObject>;
      SetNewGK: TypedContractEvent<SetNewGKEvent.InputTuple, SetNewGKEvent.OutputTuple, SetNewGKEvent.OutputObject>;
    

      'SetNewOwner(address)': TypedContractEvent<SetNewOwnerEvent.InputTuple, SetNewOwnerEvent.OutputTuple, SetNewOwnerEvent.OutputObject>;
      SetNewOwner: TypedContractEvent<SetNewOwnerEvent.InputTuple, SetNewOwnerEvent.OutputTuple, SetNewOwnerEvent.OutputObject>;
    
    };
  }