/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IRegisterOfDirectors__factory } from './IRegisterOfDirectors__factory.js';
export { RegisterOfDirectors__factory } from './RegisterOfDirectors__factory.js';