/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IRegisterOfPledges } from './IRegisterOfPledges.js';
export type { RegisterOfPledges } from './RegisterOfPledges.js';