/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../../../common.js"
  
export declare namespace PledgesRepo {
      
    export type HeadStruct = {seqOfShare: BigNumberish, seqOfPld: BigNumberish, createDate: BigNumberish, daysToMaturity: BigNumberish, guaranteeDays: BigNumberish, creditor: BigNumberish, debtor: BigNumberish, pledgor: BigNumberish, state: BigNumberish}

    export type HeadStructOutput = [seqOfShare: bigint, seqOfPld: bigint, createDate: bigint, daysToMaturity: bigint, guaranteeDays: bigint, creditor: bigint, debtor: bigint, pledgor: bigint, state: bigint] & {seqOfShare: bigint, seqOfPld: bigint, createDate: bigint, daysToMaturity: bigint, guaranteeDays: bigint, creditor: bigint, debtor: bigint, pledgor: bigint, state: bigint }
  

    export type BodyStruct = {paid: BigNumberish, par: BigNumberish, guaranteedAmt: BigNumberish, preSeq: BigNumberish, execDays: BigNumberish, para: BigNumberish, argu: BigNumberish}

    export type BodyStructOutput = [paid: bigint, par: bigint, guaranteedAmt: bigint, preSeq: bigint, execDays: bigint, para: bigint, argu: bigint] & {paid: bigint, par: bigint, guaranteedAmt: bigint, preSeq: bigint, execDays: bigint, para: bigint, argu: bigint }
  

    export type PledgeStruct = {head: PledgesRepo.HeadStruct, body: PledgesRepo.BodyStruct, hashLock: BytesLike}

    export type PledgeStructOutput = [head: PledgesRepo.HeadStructOutput, body: PledgesRepo.BodyStructOutput, hashLock: string] & {head: PledgesRepo.HeadStructOutput, body: PledgesRepo.BodyStructOutput, hashLock: string }
  
    }

  export interface RegisterOfPledgesInterface extends Interface {
    getFunction(nameOrSignature: "counterOfPledges" | "createPledge" | "execPledge" | "extendPledge" | "getAllPledges" | "getDK" | "getOwner" | "getPledge" | "getPledgesOfShare" | "getRegCenter" | "getSNList" | "init" | "initKeepers" | "isPledge" | "issuePledge" | "lockPledge" | "refundDebt" | "regPledge" | "releasePledge" | "revokePledge" | "setDirectKeeper" | "setNewGK" | "setNewOwner" | "takeBackKeys" | "transferPledge"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CreatePledge" | "ExecPledge" | "ExtendPledge" | "LockPledge" | "RefundDebt" | "ReleasePledge" | "RevokePledge" | "SetDirectKeeper" | "SetNewGK" | "SetNewOwner" | "TransferPledge"): EventFragment;

    encodeFunctionData(functionFragment: 'counterOfPledges', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createPledge', values: [BytesLike, BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'execPledge', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'extendPledge', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAllPledges', values?: undefined): string;
encodeFunctionData(functionFragment: 'getDK', values?: undefined): string;
encodeFunctionData(functionFragment: 'getOwner', values?: undefined): string;
encodeFunctionData(functionFragment: 'getPledge', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getPledgesOfShare', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRegCenter', values?: undefined): string;
encodeFunctionData(functionFragment: 'getSNList', values?: undefined): string;
encodeFunctionData(functionFragment: 'init', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'initKeepers', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'isPledge', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'issuePledge', values: [PledgesRepo.HeadStruct, BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'lockPledge', values: [BigNumberish, BigNumberish, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'refundDebt', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'regPledge', values: [PledgesRepo.PledgeStruct]): string;
encodeFunctionData(functionFragment: 'releasePledge', values: [BigNumberish, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'revokePledge', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setDirectKeeper', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setNewGK', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setNewOwner', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'takeBackKeys', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'transferPledge', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'counterOfPledges', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createPledge', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'execPledge', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'extendPledge', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllPledges', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDK', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPledge', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPledgesOfShare', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRegCenter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSNList', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'init', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initKeepers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isPledge', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'issuePledge', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lockPledge', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'refundDebt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'regPledge', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'releasePledge', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokePledge', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setDirectKeeper', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setNewGK', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setNewOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'takeBackKeys', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferPledge', data: BytesLike): Result;
  }

  
    export namespace CreatePledgeEvent {
      export type InputTuple = [seqOfShare: BigNumberish, seqOfPld: BigNumberish, creditor: BigNumberish, paid: BigNumberish, par: BigNumberish];
      export type OutputTuple = [seqOfShare: bigint, seqOfPld: bigint, creditor: bigint, paid: bigint, par: bigint];
      export interface OutputObject {seqOfShare: bigint, seqOfPld: bigint, creditor: bigint, paid: bigint, par: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ExecPledgeEvent {
      export type InputTuple = [seqOfShare: BigNumberish, seqOfPld: BigNumberish];
      export type OutputTuple = [seqOfShare: bigint, seqOfPld: bigint];
      export interface OutputObject {seqOfShare: bigint, seqOfPld: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ExtendPledgeEvent {
      export type InputTuple = [seqOfShare: BigNumberish, seqOfPld: BigNumberish, extDays: BigNumberish];
      export type OutputTuple = [seqOfShare: bigint, seqOfPld: bigint, extDays: bigint];
      export interface OutputObject {seqOfShare: bigint, seqOfPld: bigint, extDays: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LockPledgeEvent {
      export type InputTuple = [seqOfShare: BigNumberish, seqOfPld: BigNumberish, hashLock: BytesLike];
      export type OutputTuple = [seqOfShare: bigint, seqOfPld: bigint, hashLock: string];
      export interface OutputObject {seqOfShare: bigint, seqOfPld: bigint, hashLock: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RefundDebtEvent {
      export type InputTuple = [seqOfShare: BigNumberish, seqOfPld: BigNumberish, refundAmt: BigNumberish];
      export type OutputTuple = [seqOfShare: bigint, seqOfPld: bigint, refundAmt: bigint];
      export interface OutputObject {seqOfShare: bigint, seqOfPld: bigint, refundAmt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ReleasePledgeEvent {
      export type InputTuple = [seqOfShare: BigNumberish, seqOfPld: BigNumberish, hashKey: string];
      export type OutputTuple = [seqOfShare: bigint, seqOfPld: bigint, hashKey: string];
      export interface OutputObject {seqOfShare: bigint, seqOfPld: bigint, hashKey: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RevokePledgeEvent {
      export type InputTuple = [seqOfShare: BigNumberish, seqOfPld: BigNumberish];
      export type OutputTuple = [seqOfShare: bigint, seqOfPld: bigint];
      export interface OutputObject {seqOfShare: bigint, seqOfPld: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SetDirectKeeperEvent {
      export type InputTuple = [keeper: AddressLike];
      export type OutputTuple = [keeper: string];
      export interface OutputObject {keeper: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SetNewGKEvent {
      export type InputTuple = [gk: AddressLike];
      export type OutputTuple = [gk: string];
      export interface OutputObject {gk: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SetNewOwnerEvent {
      export type InputTuple = [owner: AddressLike];
      export type OutputTuple = [owner: string];
      export interface OutputObject {owner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferPledgeEvent {
      export type InputTuple = [seqOfShare: BigNumberish, seqOfPld: BigNumberish, newSeqOfPld: BigNumberish, buyer: BigNumberish, paid: BigNumberish, par: BigNumberish];
      export type OutputTuple = [seqOfShare: bigint, seqOfPld: bigint, newSeqOfPld: bigint, buyer: bigint, paid: bigint, par: bigint];
      export interface OutputObject {seqOfShare: bigint, seqOfPld: bigint, newSeqOfPld: bigint, buyer: bigint, paid: bigint, par: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface RegisterOfPledges extends BaseContract {
    
    connect(runner?: ContractRunner | null): RegisterOfPledges;
    waitForDeployment(): Promise<this>;

    interface: RegisterOfPledgesInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    counterOfPledges: TypedContractMethod<
      [seqOfShare: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    createPledge: TypedContractMethod<
      [snOfPld: BytesLike, paid: BigNumberish, par: BigNumberish, guaranteedAmt: BigNumberish, execDays: BigNumberish, ],
      [PledgesRepo.HeadStructOutput],
      'nonpayable'
    >
    

    
    execPledge: TypedContractMethod<
      [seqOfShare: BigNumberish, seqOfPld: BigNumberish, caller: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    extendPledge: TypedContractMethod<
      [seqOfShare: BigNumberish, seqOfPld: BigNumberish, extDays: BigNumberish, caller: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getAllPledges: TypedContractMethod<
      [],
      [PledgesRepo.PledgeStructOutput[]],
      'view'
    >
    

    
    getDK: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getOwner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getPledge: TypedContractMethod<
      [seqOfShare: BigNumberish, seqOfPld: BigNumberish, ],
      [PledgesRepo.PledgeStructOutput],
      'view'
    >
    

    
    getPledgesOfShare: TypedContractMethod<
      [seqOfShare: BigNumberish, ],
      [PledgesRepo.PledgeStructOutput[]],
      'view'
    >
    

    
    getRegCenter: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getSNList: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    init: TypedContractMethod<
      [owner: AddressLike, regCenter: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    initKeepers: TypedContractMethod<
      [dk: AddressLike, gk: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    isPledge: TypedContractMethod<
      [seqOfShare: BigNumberish, seqOfPledge: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    issuePledge: TypedContractMethod<
      [head: PledgesRepo.HeadStruct, paid: BigNumberish, par: BigNumberish, guaranteedAmt: BigNumberish, execDays: BigNumberish, ],
      [PledgesRepo.HeadStructOutput],
      'nonpayable'
    >
    

    
    lockPledge: TypedContractMethod<
      [seqOfShare: BigNumberish, seqOfPld: BigNumberish, hashLock: BytesLike, caller: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    refundDebt: TypedContractMethod<
      [seqOfShare: BigNumberish, seqOfPld: BigNumberish, amt: BigNumberish, caller: BigNumberish, ],
      [PledgesRepo.PledgeStructOutput],
      'nonpayable'
    >
    

    
    regPledge: TypedContractMethod<
      [pld: PledgesRepo.PledgeStruct, ],
      [PledgesRepo.HeadStructOutput],
      'nonpayable'
    >
    

    
    releasePledge: TypedContractMethod<
      [seqOfShare: BigNumberish, seqOfPld: BigNumberish, hashKey: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    revokePledge: TypedContractMethod<
      [seqOfShare: BigNumberish, seqOfPld: BigNumberish, caller: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setDirectKeeper: TypedContractMethod<
      [acct: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setNewGK: TypedContractMethod<
      [gk: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setNewOwner: TypedContractMethod<
      [acct: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    takeBackKeys: TypedContractMethod<
      [target: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    transferPledge: TypedContractMethod<
      [seqOfShare: BigNumberish, seqOfPld: BigNumberish, buyer: BigNumberish, amt: BigNumberish, caller: BigNumberish, ],
      [PledgesRepo.PledgeStructOutput],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'counterOfPledges'): TypedContractMethod<
      [seqOfShare: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'createPledge'): TypedContractMethod<
      [snOfPld: BytesLike, paid: BigNumberish, par: BigNumberish, guaranteedAmt: BigNumberish, execDays: BigNumberish, ],
      [PledgesRepo.HeadStructOutput],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'execPledge'): TypedContractMethod<
      [seqOfShare: BigNumberish, seqOfPld: BigNumberish, caller: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'extendPledge'): TypedContractMethod<
      [seqOfShare: BigNumberish, seqOfPld: BigNumberish, extDays: BigNumberish, caller: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAllPledges'): TypedContractMethod<
      [],
      [PledgesRepo.PledgeStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getDK'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getOwner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getPledge'): TypedContractMethod<
      [seqOfShare: BigNumberish, seqOfPld: BigNumberish, ],
      [PledgesRepo.PledgeStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getPledgesOfShare'): TypedContractMethod<
      [seqOfShare: BigNumberish, ],
      [PledgesRepo.PledgeStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getRegCenter'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getSNList'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'init'): TypedContractMethod<
      [owner: AddressLike, regCenter: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'initKeepers'): TypedContractMethod<
      [dk: AddressLike, gk: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'isPledge'): TypedContractMethod<
      [seqOfShare: BigNumberish, seqOfPledge: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'issuePledge'): TypedContractMethod<
      [head: PledgesRepo.HeadStruct, paid: BigNumberish, par: BigNumberish, guaranteedAmt: BigNumberish, execDays: BigNumberish, ],
      [PledgesRepo.HeadStructOutput],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'lockPledge'): TypedContractMethod<
      [seqOfShare: BigNumberish, seqOfPld: BigNumberish, hashLock: BytesLike, caller: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'refundDebt'): TypedContractMethod<
      [seqOfShare: BigNumberish, seqOfPld: BigNumberish, amt: BigNumberish, caller: BigNumberish, ],
      [PledgesRepo.PledgeStructOutput],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'regPledge'): TypedContractMethod<
      [pld: PledgesRepo.PledgeStruct, ],
      [PledgesRepo.HeadStructOutput],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'releasePledge'): TypedContractMethod<
      [seqOfShare: BigNumberish, seqOfPld: BigNumberish, hashKey: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokePledge'): TypedContractMethod<
      [seqOfShare: BigNumberish, seqOfPld: BigNumberish, caller: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setDirectKeeper'): TypedContractMethod<
      [acct: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setNewGK'): TypedContractMethod<
      [gk: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setNewOwner'): TypedContractMethod<
      [acct: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'takeBackKeys'): TypedContractMethod<
      [target: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferPledge'): TypedContractMethod<
      [seqOfShare: BigNumberish, seqOfPld: BigNumberish, buyer: BigNumberish, amt: BigNumberish, caller: BigNumberish, ],
      [PledgesRepo.PledgeStructOutput],
      'nonpayable'
    >;

    getEvent(key: 'CreatePledge'): TypedContractEvent<CreatePledgeEvent.InputTuple, CreatePledgeEvent.OutputTuple, CreatePledgeEvent.OutputObject>;
getEvent(key: 'ExecPledge'): TypedContractEvent<ExecPledgeEvent.InputTuple, ExecPledgeEvent.OutputTuple, ExecPledgeEvent.OutputObject>;
getEvent(key: 'ExtendPledge'): TypedContractEvent<ExtendPledgeEvent.InputTuple, ExtendPledgeEvent.OutputTuple, ExtendPledgeEvent.OutputObject>;
getEvent(key: 'LockPledge'): TypedContractEvent<LockPledgeEvent.InputTuple, LockPledgeEvent.OutputTuple, LockPledgeEvent.OutputObject>;
getEvent(key: 'RefundDebt'): TypedContractEvent<RefundDebtEvent.InputTuple, RefundDebtEvent.OutputTuple, RefundDebtEvent.OutputObject>;
getEvent(key: 'ReleasePledge'): TypedContractEvent<ReleasePledgeEvent.InputTuple, ReleasePledgeEvent.OutputTuple, ReleasePledgeEvent.OutputObject>;
getEvent(key: 'RevokePledge'): TypedContractEvent<RevokePledgeEvent.InputTuple, RevokePledgeEvent.OutputTuple, RevokePledgeEvent.OutputObject>;
getEvent(key: 'SetDirectKeeper'): TypedContractEvent<SetDirectKeeperEvent.InputTuple, SetDirectKeeperEvent.OutputTuple, SetDirectKeeperEvent.OutputObject>;
getEvent(key: 'SetNewGK'): TypedContractEvent<SetNewGKEvent.InputTuple, SetNewGKEvent.OutputTuple, SetNewGKEvent.OutputObject>;
getEvent(key: 'SetNewOwner'): TypedContractEvent<SetNewOwnerEvent.InputTuple, SetNewOwnerEvent.OutputTuple, SetNewOwnerEvent.OutputObject>;
getEvent(key: 'TransferPledge'): TypedContractEvent<TransferPledgeEvent.InputTuple, TransferPledgeEvent.OutputTuple, TransferPledgeEvent.OutputObject>;

    filters: {
      
      'CreatePledge(uint256,uint256,uint256,uint256,uint256)': TypedContractEvent<CreatePledgeEvent.InputTuple, CreatePledgeEvent.OutputTuple, CreatePledgeEvent.OutputObject>;
      CreatePledge: TypedContractEvent<CreatePledgeEvent.InputTuple, CreatePledgeEvent.OutputTuple, CreatePledgeEvent.OutputObject>;
    

      'ExecPledge(uint256,uint256)': TypedContractEvent<ExecPledgeEvent.InputTuple, ExecPledgeEvent.OutputTuple, ExecPledgeEvent.OutputObject>;
      ExecPledge: TypedContractEvent<ExecPledgeEvent.InputTuple, ExecPledgeEvent.OutputTuple, ExecPledgeEvent.OutputObject>;
    

      'ExtendPledge(uint256,uint256,uint256)': TypedContractEvent<ExtendPledgeEvent.InputTuple, ExtendPledgeEvent.OutputTuple, ExtendPledgeEvent.OutputObject>;
      ExtendPledge: TypedContractEvent<ExtendPledgeEvent.InputTuple, ExtendPledgeEvent.OutputTuple, ExtendPledgeEvent.OutputObject>;
    

      'LockPledge(uint256,uint256,bytes32)': TypedContractEvent<LockPledgeEvent.InputTuple, LockPledgeEvent.OutputTuple, LockPledgeEvent.OutputObject>;
      LockPledge: TypedContractEvent<LockPledgeEvent.InputTuple, LockPledgeEvent.OutputTuple, LockPledgeEvent.OutputObject>;
    

      'RefundDebt(uint256,uint256,uint256)': TypedContractEvent<RefundDebtEvent.InputTuple, RefundDebtEvent.OutputTuple, RefundDebtEvent.OutputObject>;
      RefundDebt: TypedContractEvent<RefundDebtEvent.InputTuple, RefundDebtEvent.OutputTuple, RefundDebtEvent.OutputObject>;
    

      'ReleasePledge(uint256,uint256,string)': TypedContractEvent<ReleasePledgeEvent.InputTuple, ReleasePledgeEvent.OutputTuple, ReleasePledgeEvent.OutputObject>;
      ReleasePledge: TypedContractEvent<ReleasePledgeEvent.InputTuple, ReleasePledgeEvent.OutputTuple, ReleasePledgeEvent.OutputObject>;
    

      'RevokePledge(uint256,uint256)': TypedContractEvent<RevokePledgeEvent.InputTuple, RevokePledgeEvent.OutputTuple, RevokePledgeEvent.OutputObject>;
      RevokePledge: TypedContractEvent<RevokePledgeEvent.InputTuple, RevokePledgeEvent.OutputTuple, RevokePledgeEvent.OutputObject>;
    

      'SetDirectKeeper(address)': TypedContractEvent<SetDirectKeeperEvent.InputTuple, SetDirectKeeperEvent.OutputTuple, SetDirectKeeperEvent.OutputObject>;
      SetDirectKeeper: TypedContractEvent<SetDirectKeeperEvent.InputTuple, SetDirectKeeperEvent.OutputTuple, SetDirectKeeperEvent.OutputObject>;
    

      'SetNewGK(address)': TypedContractEvent<SetNewGKEvent.InputTuple, SetNewGKEvent.OutputTuple, SetNewGKEvent.OutputObject>;
      SetNewGK: TypedContractEvent<SetNewGKEvent.InputTuple, SetNewGKEvent.OutputTuple, SetNewGKEvent.OutputObject>;
    

      'SetNewOwner(address)': TypedContractEvent<SetNewOwnerEvent.InputTuple, SetNewOwnerEvent.OutputTuple, SetNewOwnerEvent.OutputObject>;
      SetNewOwner: TypedContractEvent<SetNewOwnerEvent.InputTuple, SetNewOwnerEvent.OutputTuple, SetNewOwnerEvent.OutputObject>;
    

      'TransferPledge(uint256,uint256,uint256,uint256,uint256,uint256)': TypedContractEvent<TransferPledgeEvent.InputTuple, TransferPledgeEvent.OutputTuple, TransferPledgeEvent.OutputObject>;
      TransferPledge: TypedContractEvent<TransferPledgeEvent.InputTuple, TransferPledgeEvent.OutputTuple, TransferPledgeEvent.OutputObject>;
    
    };
  }