/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { ILockUp, ILockUpInterface } from "../../../../../comps/books/roc/terms/ILockUp.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfShare",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "keyholder",
        "type": "uint256"
      }
    ],
    "name": "addKeyholder",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfShare",
        "type": "uint256"
      }
    ],
    "name": "delLocker",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfShare",
        "type": "uint256"
      }
    ],
    "name": "getLocker",
    "outputs": [
      {
        "internalType": "uint48",
        "name": "dueDate",
        "type": "uint48"
      },
      {
        "internalType": "uint256[]",
        "name": "keyHolders",
        "type": "uint256[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "ia",
        "type": "address"
      },
      {
        "components": [
          {
            "components": [
              {
                "internalType": "uint8",
                "name": "typeOfDeal",
                "type": "uint8"
              },
              {
                "internalType": "uint16",
                "name": "seqOfDeal",
                "type": "uint16"
              },
              {
                "internalType": "uint16",
                "name": "preSeq",
                "type": "uint16"
              },
              {
                "internalType": "uint16",
                "name": "classOfShare",
                "type": "uint16"
              },
              {
                "internalType": "uint32",
                "name": "seqOfShare",
                "type": "uint32"
              },
              {
                "internalType": "uint40",
                "name": "seller",
                "type": "uint40"
              },
              {
                "internalType": "uint32",
                "name": "priceOfPaid",
                "type": "uint32"
              },
              {
                "internalType": "uint32",
                "name": "priceOfPar",
                "type": "uint32"
              },
              {
                "internalType": "uint48",
                "name": "closingDeadline",
                "type": "uint48"
              },
              {
                "internalType": "uint16",
                "name": "votingWeight",
                "type": "uint16"
              }
            ],
            "internalType": "struct DealsRepo.Head",
            "name": "head",
            "type": "tuple"
          },
          {
            "components": [
              {
                "internalType": "uint40",
                "name": "buyer",
                "type": "uint40"
              },
              {
                "internalType": "uint40",
                "name": "groupOfBuyer",
                "type": "uint40"
              },
              {
                "internalType": "uint64",
                "name": "paid",
                "type": "uint64"
              },
              {
                "internalType": "uint64",
                "name": "par",
                "type": "uint64"
              },
              {
                "internalType": "uint8",
                "name": "state",
                "type": "uint8"
              },
              {
                "internalType": "uint16",
                "name": "para",
                "type": "uint16"
              },
              {
                "internalType": "uint16",
                "name": "distrWeight",
                "type": "uint16"
              },
              {
                "internalType": "bool",
                "name": "flag",
                "type": "bool"
              }
            ],
            "internalType": "struct DealsRepo.Body",
            "name": "body",
            "type": "tuple"
          },
          {
            "internalType": "bytes32",
            "name": "hashLock",
            "type": "bytes32"
          }
        ],
        "internalType": "struct DealsRepo.Deal",
        "name": "deal",
        "type": "tuple"
      }
    ],
    "name": "isExempted",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfShare",
        "type": "uint256"
      }
    ],
    "name": "isLocked",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "components": [
          {
            "components": [
              {
                "internalType": "uint8",
                "name": "typeOfDeal",
                "type": "uint8"
              },
              {
                "internalType": "uint16",
                "name": "seqOfDeal",
                "type": "uint16"
              },
              {
                "internalType": "uint16",
                "name": "preSeq",
                "type": "uint16"
              },
              {
                "internalType": "uint16",
                "name": "classOfShare",
                "type": "uint16"
              },
              {
                "internalType": "uint32",
                "name": "seqOfShare",
                "type": "uint32"
              },
              {
                "internalType": "uint40",
                "name": "seller",
                "type": "uint40"
              },
              {
                "internalType": "uint32",
                "name": "priceOfPaid",
                "type": "uint32"
              },
              {
                "internalType": "uint32",
                "name": "priceOfPar",
                "type": "uint32"
              },
              {
                "internalType": "uint48",
                "name": "closingDeadline",
                "type": "uint48"
              },
              {
                "internalType": "uint16",
                "name": "votingWeight",
                "type": "uint16"
              }
            ],
            "internalType": "struct DealsRepo.Head",
            "name": "head",
            "type": "tuple"
          },
          {
            "components": [
              {
                "internalType": "uint40",
                "name": "buyer",
                "type": "uint40"
              },
              {
                "internalType": "uint40",
                "name": "groupOfBuyer",
                "type": "uint40"
              },
              {
                "internalType": "uint64",
                "name": "paid",
                "type": "uint64"
              },
              {
                "internalType": "uint64",
                "name": "par",
                "type": "uint64"
              },
              {
                "internalType": "uint8",
                "name": "state",
                "type": "uint8"
              },
              {
                "internalType": "uint16",
                "name": "para",
                "type": "uint16"
              },
              {
                "internalType": "uint16",
                "name": "distrWeight",
                "type": "uint16"
              },
              {
                "internalType": "bool",
                "name": "flag",
                "type": "bool"
              }
            ],
            "internalType": "struct DealsRepo.Body",
            "name": "body",
            "type": "tuple"
          },
          {
            "internalType": "bytes32",
            "name": "hashLock",
            "type": "bytes32"
          }
        ],
        "internalType": "struct DealsRepo.Deal",
        "name": "deal",
        "type": "tuple"
      }
    ],
    "name": "isTriggered",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "lockedShares",
    "outputs": [
      {
        "internalType": "uint256[]",
        "name": "",
        "type": "uint256[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfShare",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "keyholder",
        "type": "uint256"
      }
    ],
    "name": "removeKeyholder",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seqOfShare",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "dueDate",
        "type": "uint256"
      }
    ],
    "name": "setLocker",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class ILockUp__factory {
    static readonly abi = _abi;
    static createInterface(): ILockUpInterface {
      return new Interface(_abi) as ILockUpInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): ILockUp {
      return new Contract(address, _abi, runner) as unknown as ILockUp;
    }
  }
  