/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../../../common.js"
  
export declare namespace RedemptionsRepo {
      
    export type RequestStruct = {class: BigNumberish, seqOfShare: BigNumberish, navPrice: BigNumberish, shareholder: BigNumberish, paid: BigNumberish, value: BigNumberish, seqOfPacks: BigNumberish}

    export type RequestStructOutput = [class_: bigint, seqOfShare: bigint, navPrice: bigint, shareholder: bigint, paid: bigint, value: bigint, seqOfPacks: bigint] & {class: bigint, seqOfShare: bigint, navPrice: bigint, shareholder: bigint, paid: bigint, value: bigint, seqOfPacks: bigint }
  
    }

  export interface RegisterOfRedemptionsInterface extends Interface {
    getFunction(nameOrSignature: "addRedeemableClass" | "getClassesList" | "getDK" | "getInfoOfClass" | "getInfoOfPack" | "getOwner" | "getPacksList" | "getRegCenter" | "getRequest" | "getRequests" | "getSharesList" | "init" | "initKeepers" | "isRedeemable" | "redeem" | "removeRedeemableClass" | "requestForRedemption" | "setDirectKeeper" | "setNewGK" | "setNewOwner" | "takeBackKeys" | "updateNavPrice"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AddRedeemableClass" | "RedeemClass" | "RedeemShare" | "RemoveRedeemableClass" | "RequestForRedemption" | "SetDirectKeeper" | "SetNewGK" | "SetNewOwner" | "UpdateNavPrice"): EventFragment;

    encodeFunctionData(functionFragment: 'addRedeemableClass', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getClassesList', values?: undefined): string;
encodeFunctionData(functionFragment: 'getDK', values?: undefined): string;
encodeFunctionData(functionFragment: 'getInfoOfClass', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getInfoOfPack', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getOwner', values?: undefined): string;
encodeFunctionData(functionFragment: 'getPacksList', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRegCenter', values?: undefined): string;
encodeFunctionData(functionFragment: 'getRequest', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRequests', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getSharesList', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'init', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'initKeepers', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'isRedeemable', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'redeem', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'removeRedeemableClass', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'requestForRedemption', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setDirectKeeper', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setNewGK', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setNewOwner', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'takeBackKeys', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateNavPrice', values: [BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'addRedeemableClass', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getClassesList', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDK', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getInfoOfClass', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getInfoOfPack', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPacksList', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRegCenter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRequest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRequests', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSharesList', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'init', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initKeepers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isRedeemable', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'redeem', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeRedeemableClass', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requestForRedemption', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setDirectKeeper', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setNewGK', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setNewOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'takeBackKeys', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateNavPrice', data: BytesLike): Result;
  }

  
    export namespace AddRedeemableClassEvent {
      export type InputTuple = [class_: BigNumberish];
      export type OutputTuple = [class_: bigint];
      export interface OutputObject {class: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RedeemClassEvent {
      export type InputTuple = [class_: BigNumberish, sumOfPaid: BigNumberish, totalValue: BigNumberish];
      export type OutputTuple = [class_: bigint, sumOfPaid: bigint, totalValue: bigint];
      export interface OutputObject {class: bigint, sumOfPaid: bigint, totalValue: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RedeemShareEvent {
      export type InputTuple = [shareholder: BigNumberish, class_: BigNumberish, seqOfShare: BigNumberish, paid: BigNumberish, value: BigNumberish];
      export type OutputTuple = [shareholder: bigint, class_: bigint, seqOfShare: bigint, paid: bigint, value: bigint];
      export interface OutputObject {shareholder: bigint, class: bigint, seqOfShare: bigint, paid: bigint, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RemoveRedeemableClassEvent {
      export type InputTuple = [class_: BigNumberish];
      export type OutputTuple = [class_: bigint];
      export interface OutputObject {class: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RequestForRedemptionEvent {
      export type InputTuple = [class_: BigNumberish, seqOfShare: BigNumberish, paid: BigNumberish, value: BigNumberish];
      export type OutputTuple = [class_: bigint, seqOfShare: bigint, paid: bigint, value: bigint];
      export interface OutputObject {class: bigint, seqOfShare: bigint, paid: bigint, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SetDirectKeeperEvent {
      export type InputTuple = [keeper: AddressLike];
      export type OutputTuple = [keeper: string];
      export interface OutputObject {keeper: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SetNewGKEvent {
      export type InputTuple = [gk: AddressLike];
      export type OutputTuple = [gk: string];
      export interface OutputObject {gk: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SetNewOwnerEvent {
      export type InputTuple = [owner: AddressLike];
      export type OutputTuple = [owner: string];
      export interface OutputObject {owner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UpdateNavPriceEvent {
      export type InputTuple = [class_: BigNumberish, price: BigNumberish];
      export type OutputTuple = [class_: bigint, price: bigint];
      export interface OutputObject {class: bigint, price: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface RegisterOfRedemptions extends BaseContract {
    
    connect(runner?: ContractRunner | null): RegisterOfRedemptions;
    waitForDeployment(): Promise<this>;

    interface: RegisterOfRedemptionsInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addRedeemableClass: TypedContractMethod<
      [class: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getClassesList: TypedContractMethod<
      [],
      [bigint[]],
      'view'
    >
    

    
    getDK: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getInfoOfClass: TypedContractMethod<
      [class: BigNumberish, ],
      [RedemptionsRepo.RequestStructOutput],
      'view'
    >
    

    
    getInfoOfPack: TypedContractMethod<
      [class: BigNumberish, seqOfPack: BigNumberish, ],
      [RedemptionsRepo.RequestStructOutput],
      'view'
    >
    

    
    getOwner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getPacksList: TypedContractMethod<
      [class: BigNumberish, ],
      [bigint[]],
      'view'
    >
    

    
    getRegCenter: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getRequest: TypedContractMethod<
      [class: BigNumberish, seqOfPack: BigNumberish, seqOfShare: BigNumberish, ],
      [RedemptionsRepo.RequestStructOutput],
      'view'
    >
    

    
    getRequests: TypedContractMethod<
      [class: BigNumberish, seqOfPack: BigNumberish, ],
      [RedemptionsRepo.RequestStructOutput[]],
      'view'
    >
    

    
    getSharesList: TypedContractMethod<
      [class: BigNumberish, seqOfPack: BigNumberish, ],
      [bigint[]],
      'view'
    >
    

    
    init: TypedContractMethod<
      [owner: AddressLike, regCenter: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    initKeepers: TypedContractMethod<
      [dk: AddressLike, gk: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    isRedeemable: TypedContractMethod<
      [class: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    redeem: TypedContractMethod<
      [class: BigNumberish, seqOfPack: BigNumberish, ],
      [[RedemptionsRepo.RequestStructOutput[], RedemptionsRepo.RequestStructOutput] & {list: RedemptionsRepo.RequestStructOutput[], info: RedemptionsRepo.RequestStructOutput }],
      'nonpayable'
    >
    

    
    removeRedeemableClass: TypedContractMethod<
      [class: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    requestForRedemption: TypedContractMethod<
      [caller: BigNumberish, class: BigNumberish, seqOfShare: BigNumberish, paid: BigNumberish, ],
      [RedemptionsRepo.RequestStructOutput],
      'nonpayable'
    >
    

    
    setDirectKeeper: TypedContractMethod<
      [acct: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setNewGK: TypedContractMethod<
      [gk: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setNewOwner: TypedContractMethod<
      [acct: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    takeBackKeys: TypedContractMethod<
      [target: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateNavPrice: TypedContractMethod<
      [class: BigNumberish, price: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addRedeemableClass'): TypedContractMethod<
      [class: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getClassesList'): TypedContractMethod<
      [],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getDK'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getInfoOfClass'): TypedContractMethod<
      [class: BigNumberish, ],
      [RedemptionsRepo.RequestStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getInfoOfPack'): TypedContractMethod<
      [class: BigNumberish, seqOfPack: BigNumberish, ],
      [RedemptionsRepo.RequestStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getOwner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getPacksList'): TypedContractMethod<
      [class: BigNumberish, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getRegCenter'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getRequest'): TypedContractMethod<
      [class: BigNumberish, seqOfPack: BigNumberish, seqOfShare: BigNumberish, ],
      [RedemptionsRepo.RequestStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getRequests'): TypedContractMethod<
      [class: BigNumberish, seqOfPack: BigNumberish, ],
      [RedemptionsRepo.RequestStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getSharesList'): TypedContractMethod<
      [class: BigNumberish, seqOfPack: BigNumberish, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'init'): TypedContractMethod<
      [owner: AddressLike, regCenter: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'initKeepers'): TypedContractMethod<
      [dk: AddressLike, gk: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'isRedeemable'): TypedContractMethod<
      [class: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'redeem'): TypedContractMethod<
      [class: BigNumberish, seqOfPack: BigNumberish, ],
      [[RedemptionsRepo.RequestStructOutput[], RedemptionsRepo.RequestStructOutput] & {list: RedemptionsRepo.RequestStructOutput[], info: RedemptionsRepo.RequestStructOutput }],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'removeRedeemableClass'): TypedContractMethod<
      [class: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'requestForRedemption'): TypedContractMethod<
      [caller: BigNumberish, class: BigNumberish, seqOfShare: BigNumberish, paid: BigNumberish, ],
      [RedemptionsRepo.RequestStructOutput],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setDirectKeeper'): TypedContractMethod<
      [acct: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setNewGK'): TypedContractMethod<
      [gk: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setNewOwner'): TypedContractMethod<
      [acct: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'takeBackKeys'): TypedContractMethod<
      [target: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateNavPrice'): TypedContractMethod<
      [class: BigNumberish, price: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AddRedeemableClass'): TypedContractEvent<AddRedeemableClassEvent.InputTuple, AddRedeemableClassEvent.OutputTuple, AddRedeemableClassEvent.OutputObject>;
getEvent(key: 'RedeemClass'): TypedContractEvent<RedeemClassEvent.InputTuple, RedeemClassEvent.OutputTuple, RedeemClassEvent.OutputObject>;
getEvent(key: 'RedeemShare'): TypedContractEvent<RedeemShareEvent.InputTuple, RedeemShareEvent.OutputTuple, RedeemShareEvent.OutputObject>;
getEvent(key: 'RemoveRedeemableClass'): TypedContractEvent<RemoveRedeemableClassEvent.InputTuple, RemoveRedeemableClassEvent.OutputTuple, RemoveRedeemableClassEvent.OutputObject>;
getEvent(key: 'RequestForRedemption'): TypedContractEvent<RequestForRedemptionEvent.InputTuple, RequestForRedemptionEvent.OutputTuple, RequestForRedemptionEvent.OutputObject>;
getEvent(key: 'SetDirectKeeper'): TypedContractEvent<SetDirectKeeperEvent.InputTuple, SetDirectKeeperEvent.OutputTuple, SetDirectKeeperEvent.OutputObject>;
getEvent(key: 'SetNewGK'): TypedContractEvent<SetNewGKEvent.InputTuple, SetNewGKEvent.OutputTuple, SetNewGKEvent.OutputObject>;
getEvent(key: 'SetNewOwner'): TypedContractEvent<SetNewOwnerEvent.InputTuple, SetNewOwnerEvent.OutputTuple, SetNewOwnerEvent.OutputObject>;
getEvent(key: 'UpdateNavPrice'): TypedContractEvent<UpdateNavPriceEvent.InputTuple, UpdateNavPriceEvent.OutputTuple, UpdateNavPriceEvent.OutputObject>;

    filters: {
      
      'AddRedeemableClass(uint256)': TypedContractEvent<AddRedeemableClassEvent.InputTuple, AddRedeemableClassEvent.OutputTuple, AddRedeemableClassEvent.OutputObject>;
      AddRedeemableClass: TypedContractEvent<AddRedeemableClassEvent.InputTuple, AddRedeemableClassEvent.OutputTuple, AddRedeemableClassEvent.OutputObject>;
    

      'RedeemClass(uint256,uint256,uint256)': TypedContractEvent<RedeemClassEvent.InputTuple, RedeemClassEvent.OutputTuple, RedeemClassEvent.OutputObject>;
      RedeemClass: TypedContractEvent<RedeemClassEvent.InputTuple, RedeemClassEvent.OutputTuple, RedeemClassEvent.OutputObject>;
    

      'RedeemShare(uint256,uint256,uint256,uint256,uint256)': TypedContractEvent<RedeemShareEvent.InputTuple, RedeemShareEvent.OutputTuple, RedeemShareEvent.OutputObject>;
      RedeemShare: TypedContractEvent<RedeemShareEvent.InputTuple, RedeemShareEvent.OutputTuple, RedeemShareEvent.OutputObject>;
    

      'RemoveRedeemableClass(uint256)': TypedContractEvent<RemoveRedeemableClassEvent.InputTuple, RemoveRedeemableClassEvent.OutputTuple, RemoveRedeemableClassEvent.OutputObject>;
      RemoveRedeemableClass: TypedContractEvent<RemoveRedeemableClassEvent.InputTuple, RemoveRedeemableClassEvent.OutputTuple, RemoveRedeemableClassEvent.OutputObject>;
    

      'RequestForRedemption(uint256,uint256,uint256,uint256)': TypedContractEvent<RequestForRedemptionEvent.InputTuple, RequestForRedemptionEvent.OutputTuple, RequestForRedemptionEvent.OutputObject>;
      RequestForRedemption: TypedContractEvent<RequestForRedemptionEvent.InputTuple, RequestForRedemptionEvent.OutputTuple, RequestForRedemptionEvent.OutputObject>;
    

      'SetDirectKeeper(address)': TypedContractEvent<SetDirectKeeperEvent.InputTuple, SetDirectKeeperEvent.OutputTuple, SetDirectKeeperEvent.OutputObject>;
      SetDirectKeeper: TypedContractEvent<SetDirectKeeperEvent.InputTuple, SetDirectKeeperEvent.OutputTuple, SetDirectKeeperEvent.OutputObject>;
    

      'SetNewGK(address)': TypedContractEvent<SetNewGKEvent.InputTuple, SetNewGKEvent.OutputTuple, SetNewGKEvent.OutputObject>;
      SetNewGK: TypedContractEvent<SetNewGKEvent.InputTuple, SetNewGKEvent.OutputTuple, SetNewGKEvent.OutputObject>;
    

      'SetNewOwner(address)': TypedContractEvent<SetNewOwnerEvent.InputTuple, SetNewOwnerEvent.OutputTuple, SetNewOwnerEvent.OutputObject>;
      SetNewOwner: TypedContractEvent<SetNewOwnerEvent.InputTuple, SetNewOwnerEvent.OutputTuple, SetNewOwnerEvent.OutputObject>;
    

      'UpdateNavPrice(uint256,uint256)': TypedContractEvent<UpdateNavPriceEvent.InputTuple, UpdateNavPriceEvent.OutputTuple, UpdateNavPriceEvent.OutputObject>;
      UpdateNavPrice: TypedContractEvent<UpdateNavPriceEvent.InputTuple, UpdateNavPriceEvent.OutputTuple, UpdateNavPriceEvent.OutputObject>;
    
    };
  }