/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace ICashier {
      
    export type TransferAuthStruct = {from: AddressLike, to: AddressLike, value: BigNumberish, validAfter: BigNumberish, validBefore: BigNumberish, nonce: BytesLike, v: BigNumberish, r: BytesLike, s: BytesLike}

    export type TransferAuthStructOutput = [from: string, to: string, value: bigint, validAfter: bigint, validBefore: bigint, nonce: string, v: bigint, r: string, s: string] & {from: string, to: string, value: bigint, validAfter: bigint, validBefore: bigint, nonce: string, v: bigint, r: string, s: string }
  
    }

  export interface UsdFuelTankInterface extends Interface {
    getFunction(nameOrSignature: "cashier" | "getOwner" | "getRegCenter" | "init" | "rate" | "refuel" | "setCashier" | "setNewOwner" | "setRate" | "sum" | "withdrawFuel"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Refuel" | "SetCashier" | "SetNewOwner" | "SetRate" | "WithdrawFuel"): EventFragment;

    encodeFunctionData(functionFragment: 'cashier', values?: undefined): string;
encodeFunctionData(functionFragment: 'getOwner', values?: undefined): string;
encodeFunctionData(functionFragment: 'getRegCenter', values?: undefined): string;
encodeFunctionData(functionFragment: 'init', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'rate', values?: undefined): string;
encodeFunctionData(functionFragment: 'refuel', values: [ICashier.TransferAuthStruct, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setCashier', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setNewOwner', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setRate', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'sum', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdrawFuel', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'cashier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRegCenter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'init', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'refuel', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setCashier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setNewOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setRate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'sum', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawFuel', data: BytesLike): Result;
  }

  
    export namespace RefuelEvent {
      export type InputTuple = [buyer: AddressLike, amtOfUSDC: BigNumberish, amtOfCbp: BigNumberish];
      export type OutputTuple = [buyer: string, amtOfUSDC: bigint, amtOfCbp: bigint];
      export interface OutputObject {buyer: string, amtOfUSDC: bigint, amtOfCbp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SetCashierEvent {
      export type InputTuple = [newCashier: AddressLike];
      export type OutputTuple = [newCashier: string];
      export interface OutputObject {newCashier: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SetNewOwnerEvent {
      export type InputTuple = [owner: AddressLike];
      export type OutputTuple = [owner: string];
      export interface OutputObject {owner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SetRateEvent {
      export type InputTuple = [newRate: BigNumberish];
      export type OutputTuple = [newRate: bigint];
      export interface OutputObject {newRate: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawFuelEvent {
      export type InputTuple = [owner: AddressLike, amt: BigNumberish];
      export type OutputTuple = [owner: string, amt: bigint];
      export interface OutputObject {owner: string, amt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface UsdFuelTank extends BaseContract {
    
    connect(runner?: ContractRunner | null): UsdFuelTank;
    waitForDeployment(): Promise<this>;

    interface: UsdFuelTankInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    cashier: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getOwner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getRegCenter: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    init: TypedContractMethod<
      [owner: AddressLike, regCenter: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    rate: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    refuel: TypedContractMethod<
      [auth: ICashier.TransferAuthStruct, amt: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setCashier: TypedContractMethod<
      [newCashier: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setNewOwner: TypedContractMethod<
      [acct: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setRate: TypedContractMethod<
      [newRate: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    sum: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    withdrawFuel: TypedContractMethod<
      [amt: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'cashier'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getOwner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getRegCenter'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'init'): TypedContractMethod<
      [owner: AddressLike, regCenter: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'rate'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'refuel'): TypedContractMethod<
      [auth: ICashier.TransferAuthStruct, amt: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setCashier'): TypedContractMethod<
      [newCashier: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setNewOwner'): TypedContractMethod<
      [acct: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setRate'): TypedContractMethod<
      [newRate: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'sum'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'withdrawFuel'): TypedContractMethod<
      [amt: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'Refuel'): TypedContractEvent<RefuelEvent.InputTuple, RefuelEvent.OutputTuple, RefuelEvent.OutputObject>;
getEvent(key: 'SetCashier'): TypedContractEvent<SetCashierEvent.InputTuple, SetCashierEvent.OutputTuple, SetCashierEvent.OutputObject>;
getEvent(key: 'SetNewOwner'): TypedContractEvent<SetNewOwnerEvent.InputTuple, SetNewOwnerEvent.OutputTuple, SetNewOwnerEvent.OutputObject>;
getEvent(key: 'SetRate'): TypedContractEvent<SetRateEvent.InputTuple, SetRateEvent.OutputTuple, SetRateEvent.OutputObject>;
getEvent(key: 'WithdrawFuel'): TypedContractEvent<WithdrawFuelEvent.InputTuple, WithdrawFuelEvent.OutputTuple, WithdrawFuelEvent.OutputObject>;

    filters: {
      
      'Refuel(address,uint256,uint256)': TypedContractEvent<RefuelEvent.InputTuple, RefuelEvent.OutputTuple, RefuelEvent.OutputObject>;
      Refuel: TypedContractEvent<RefuelEvent.InputTuple, RefuelEvent.OutputTuple, RefuelEvent.OutputObject>;
    

      'SetCashier(address)': TypedContractEvent<SetCashierEvent.InputTuple, SetCashierEvent.OutputTuple, SetCashierEvent.OutputObject>;
      SetCashier: TypedContractEvent<SetCashierEvent.InputTuple, SetCashierEvent.OutputTuple, SetCashierEvent.OutputObject>;
    

      'SetNewOwner(address)': TypedContractEvent<SetNewOwnerEvent.InputTuple, SetNewOwnerEvent.OutputTuple, SetNewOwnerEvent.OutputObject>;
      SetNewOwner: TypedContractEvent<SetNewOwnerEvent.InputTuple, SetNewOwnerEvent.OutputTuple, SetNewOwnerEvent.OutputObject>;
    

      'SetRate(uint256)': TypedContractEvent<SetRateEvent.InputTuple, SetRateEvent.OutputTuple, SetRateEvent.OutputObject>;
      SetRate: TypedContractEvent<SetRateEvent.InputTuple, SetRateEvent.OutputTuple, SetRateEvent.OutputObject>;
    

      'WithdrawFuel(address,uint256)': TypedContractEvent<WithdrawFuelEvent.InputTuple, WithdrawFuelEvent.OutputTuple, WithdrawFuelEvent.OutputObject>;
      WithdrawFuel: TypedContractEvent<WithdrawFuelEvent.InputTuple, WithdrawFuelEvent.OutputTuple, WithdrawFuelEvent.OutputObject>;
    
    };
  }