/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IInvestmentAgreement__factory } from './IInvestmentAgreement__factory.js';
export { IRegisterOfAgreements__factory } from './IRegisterOfAgreements__factory.js';
export { InvestmentAgreement__factory } from './InvestmentAgreement__factory.js';
export { RegisterOfAgreements__factory } from './RegisterOfAgreements__factory.js';