/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../../../common.js"
  
export declare namespace OptionsRepo {
      
    export type HeadStruct = {seqOfOpt: BigNumberish, typeOfOpt: BigNumberish, classOfShare: BigNumberish, rate: BigNumberish, issueDate: BigNumberish, triggerDate: BigNumberish, execDays: BigNumberish, closingDays: BigNumberish, obligor: BigNumberish}

    export type HeadStructOutput = [seqOfOpt: bigint, typeOfOpt: bigint, classOfShare: bigint, rate: bigint, issueDate: bigint, triggerDate: bigint, execDays: bigint, closingDays: bigint, obligor: bigint] & {seqOfOpt: bigint, typeOfOpt: bigint, classOfShare: bigint, rate: bigint, issueDate: bigint, triggerDate: bigint, execDays: bigint, closingDays: bigint, obligor: bigint }
  

    export type BodyStruct = {closingDeadline: BigNumberish, rightholder: BigNumberish, paid: BigNumberish, par: BigNumberish, state: BigNumberish, para: BigNumberish, argu: BigNumberish}

    export type BodyStructOutput = [closingDeadline: bigint, rightholder: bigint, paid: bigint, par: bigint, state: bigint, para: bigint, argu: bigint] & {closingDeadline: bigint, rightholder: bigint, paid: bigint, par: bigint, state: bigint, para: bigint, argu: bigint }
  

    export type OptionStruct = {head: OptionsRepo.HeadStruct, cond: CondsRepo.CondStruct, body: OptionsRepo.BodyStruct}

    export type OptionStructOutput = [head: OptionsRepo.HeadStructOutput, cond: CondsRepo.CondStructOutput, body: OptionsRepo.BodyStructOutput] & {head: OptionsRepo.HeadStructOutput, cond: CondsRepo.CondStructOutput, body: OptionsRepo.BodyStructOutput }
  
    }

export declare namespace SwapsRepo {
      
    export type SwapStruct = {seqOfSwap: BigNumberish, seqOfPledge: BigNumberish, paidOfPledge: BigNumberish, seqOfTarget: BigNumberish, paidOfTarget: BigNumberish, priceOfDeal: BigNumberish, isPutOpt: boolean, state: BigNumberish}

    export type SwapStructOutput = [seqOfSwap: bigint, seqOfPledge: bigint, paidOfPledge: bigint, seqOfTarget: bigint, paidOfTarget: bigint, priceOfDeal: bigint, isPutOpt: boolean, state: bigint] & {seqOfSwap: bigint, seqOfPledge: bigint, paidOfPledge: bigint, seqOfTarget: bigint, paidOfTarget: bigint, priceOfDeal: bigint, isPutOpt: boolean, state: bigint }
  
    }

export declare namespace CondsRepo {
      
    export type CondStruct = {seqOfCond: BigNumberish, logicOpr: BigNumberish, compOpr1: BigNumberish, para1: BigNumberish, compOpr2: BigNumberish, para2: BigNumberish, compOpr3: BigNumberish, para3: BigNumberish}

    export type CondStructOutput = [seqOfCond: bigint, logicOpr: bigint, compOpr1: bigint, para1: bigint, compOpr2: bigint, para2: bigint, compOpr3: bigint, para3: bigint] & {seqOfCond: bigint, logicOpr: bigint, compOpr1: bigint, para1: bigint, compOpr2: bigint, para2: bigint, compOpr3: bigint, para3: bigint }
  
    }

export declare namespace Checkpoints {
      
    export type CheckpointStruct = {timestamp: BigNumberish, rate: BigNumberish, paid: BigNumberish, par: BigNumberish, points: BigNumberish}

    export type CheckpointStructOutput = [timestamp: bigint, rate: bigint, paid: bigint, par: bigint, points: bigint] & {timestamp: bigint, rate: bigint, paid: bigint, par: bigint, points: bigint }
  
    }

  export interface IRegisterOfOptionsInterface extends Interface {
    getFunction(nameOrSignature: "addObligorIntoOption" | "allSwapsClosed" | "counterOfOptions" | "counterOfSwaps" | "createOption" | "createSwap" | "execOption" | "getAllOptions" | "getAllOraclesOfOption" | "getAllSwapsOfOption" | "getLatestOracle" | "getObligorsOfOption" | "getOption" | "getOracleAtDate" | "getSeqListOfOptions" | "getSwap" | "isObligor" | "isOption" | "isRightholder" | "isSwap" | "issueOption" | "payOffSwap" | "qtyOfOptions" | "regOptionTerms" | "removeObligorFromOption" | "sumPaidOfTarget" | "terminateSwap" | "updateOracle"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AddObligorIntoOpt" | "CreateOpt" | "ExecOpt" | "IssueOpt" | "PayOffSwap" | "RegSwap" | "RemoveObligorFromOpt" | "TerminateSwap" | "UpdateOracle"): EventFragment;

    encodeFunctionData(functionFragment: 'addObligorIntoOption', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'allSwapsClosed', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'counterOfOptions', values?: undefined): string;
encodeFunctionData(functionFragment: 'counterOfSwaps', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createOption', values: [BytesLike, BytesLike, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'createSwap', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'execOption', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAllOptions', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAllOraclesOfOption', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAllSwapsOfOption', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getLatestOracle', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getObligorsOfOption', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getOption', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getOracleAtDate', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getSeqListOfOptions', values?: undefined): string;
encodeFunctionData(functionFragment: 'getSwap', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'isObligor', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'isOption', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'isRightholder', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'isSwap', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'issueOption', values: [OptionsRepo.OptionStruct]): string;
encodeFunctionData(functionFragment: 'payOffSwap', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'qtyOfOptions', values?: undefined): string;
encodeFunctionData(functionFragment: 'regOptionTerms', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'removeObligorFromOption', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'sumPaidOfTarget', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'terminateSwap', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'updateOracle', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'addObligorIntoOption', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allSwapsClosed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'counterOfOptions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'counterOfSwaps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createOption', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createSwap', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'execOption', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllOptions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllOraclesOfOption', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllSwapsOfOption', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getLatestOracle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getObligorsOfOption', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOption', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOracleAtDate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSeqListOfOptions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSwap', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isObligor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isOption', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isRightholder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isSwap', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'issueOption', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'payOffSwap', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'qtyOfOptions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'regOptionTerms', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeObligorFromOption', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'sumPaidOfTarget', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'terminateSwap', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateOracle', data: BytesLike): Result;
  }

  
    export namespace AddObligorIntoOptEvent {
      export type InputTuple = [seqOfOpt: BigNumberish, obligor: BigNumberish];
      export type OutputTuple = [seqOfOpt: bigint, obligor: bigint];
      export interface OutputObject {seqOfOpt: bigint, obligor: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CreateOptEvent {
      export type InputTuple = [seqOfOpt: BigNumberish, codeOfOpt: BytesLike];
      export type OutputTuple = [seqOfOpt: bigint, codeOfOpt: string];
      export interface OutputObject {seqOfOpt: bigint, codeOfOpt: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ExecOptEvent {
      export type InputTuple = [seqOfOpt: BigNumberish];
      export type OutputTuple = [seqOfOpt: bigint];
      export interface OutputObject {seqOfOpt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace IssueOptEvent {
      export type InputTuple = [seqOfOpt: BigNumberish, issueDate: BigNumberish];
      export type OutputTuple = [seqOfOpt: bigint, issueDate: bigint];
      export interface OutputObject {seqOfOpt: bigint, issueDate: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PayOffSwapEvent {
      export type InputTuple = [seqOfOpt: BigNumberish, snOfSwap: BytesLike];
      export type OutputTuple = [seqOfOpt: bigint, snOfSwap: string];
      export interface OutputObject {seqOfOpt: bigint, snOfSwap: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RegSwapEvent {
      export type InputTuple = [seqOfOpt: BigNumberish, snOfSwap: BytesLike];
      export type OutputTuple = [seqOfOpt: bigint, snOfSwap: string];
      export interface OutputObject {seqOfOpt: bigint, snOfSwap: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RemoveObligorFromOptEvent {
      export type InputTuple = [seqOfOpt: BigNumberish, obligor: BigNumberish];
      export type OutputTuple = [seqOfOpt: bigint, obligor: bigint];
      export interface OutputObject {seqOfOpt: bigint, obligor: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TerminateSwapEvent {
      export type InputTuple = [seqOfOpt: BigNumberish, seqOfSwap: BigNumberish];
      export type OutputTuple = [seqOfOpt: bigint, seqOfSwap: bigint];
      export interface OutputObject {seqOfOpt: bigint, seqOfSwap: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UpdateOracleEvent {
      export type InputTuple = [seqOfOpt: BigNumberish, data1: BigNumberish, data2: BigNumberish, data3: BigNumberish];
      export type OutputTuple = [seqOfOpt: bigint, data1: bigint, data2: bigint, data3: bigint];
      export interface OutputObject {seqOfOpt: bigint, data1: bigint, data2: bigint, data3: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface IRegisterOfOptions extends BaseContract {
    
    connect(runner?: ContractRunner | null): IRegisterOfOptions;
    waitForDeployment(): Promise<this>;

    interface: IRegisterOfOptionsInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addObligorIntoOption: TypedContractMethod<
      [seqOfOpt: BigNumberish, obligor: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    allSwapsClosed: TypedContractMethod<
      [seqOfOpt: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    counterOfOptions: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    counterOfSwaps: TypedContractMethod<
      [seqOfOpt: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    createOption: TypedContractMethod<
      [sn: BytesLike, snOfCond: BytesLike, rightholder: BigNumberish, paid: BigNumberish, par: BigNumberish, ],
      [OptionsRepo.HeadStructOutput],
      'nonpayable'
    >
    

    
    createSwap: TypedContractMethod<
      [seqOfOpt: BigNumberish, seqOfTarget: BigNumberish, paidOfTarget: BigNumberish, seqOfPledge: BigNumberish, caller: BigNumberish, ],
      [SwapsRepo.SwapStructOutput],
      'nonpayable'
    >
    

    
    execOption: TypedContractMethod<
      [seqOfOpt: BigNumberish, caller: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getAllOptions: TypedContractMethod<
      [],
      [OptionsRepo.OptionStructOutput[]],
      'view'
    >
    

    
    getAllOraclesOfOption: TypedContractMethod<
      [seqOfOpt: BigNumberish, ],
      [Checkpoints.CheckpointStructOutput[]],
      'view'
    >
    

    
    getAllSwapsOfOption: TypedContractMethod<
      [seqOfOpt: BigNumberish, ],
      [SwapsRepo.SwapStructOutput[]],
      'view'
    >
    

    
    getLatestOracle: TypedContractMethod<
      [seqOfOpt: BigNumberish, ],
      [Checkpoints.CheckpointStructOutput],
      'view'
    >
    

    
    getObligorsOfOption: TypedContractMethod<
      [seqOfOpt: BigNumberish, ],
      [bigint[]],
      'view'
    >
    

    
    getOption: TypedContractMethod<
      [seqOfOpt: BigNumberish, ],
      [OptionsRepo.OptionStructOutput],
      'view'
    >
    

    
    getOracleAtDate: TypedContractMethod<
      [seqOfOpt: BigNumberish, date: BigNumberish, ],
      [Checkpoints.CheckpointStructOutput],
      'view'
    >
    

    
    getSeqListOfOptions: TypedContractMethod<
      [],
      [bigint[]],
      'view'
    >
    

    
    getSwap: TypedContractMethod<
      [seqOfOpt: BigNumberish, seqOfSwap: BigNumberish, ],
      [SwapsRepo.SwapStructOutput],
      'view'
    >
    

    
    isObligor: TypedContractMethod<
      [seqOfOpt: BigNumberish, acct: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    isOption: TypedContractMethod<
      [seqOfOpt: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    isRightholder: TypedContractMethod<
      [seqOfOpt: BigNumberish, acct: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    isSwap: TypedContractMethod<
      [seqOfOpt: BigNumberish, seqOfSwap: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    issueOption: TypedContractMethod<
      [opt: OptionsRepo.OptionStruct, ],
      [void],
      'nonpayable'
    >
    

    
    payOffSwap: TypedContractMethod<
      [seqOfOpt: BigNumberish, seqOfSwap: BigNumberish, ],
      [SwapsRepo.SwapStructOutput],
      'nonpayable'
    >
    

    
    qtyOfOptions: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    regOptionTerms: TypedContractMethod<
      [opts: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    removeObligorFromOption: TypedContractMethod<
      [seqOfOpt: BigNumberish, obligor: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    sumPaidOfTarget: TypedContractMethod<
      [seqOfOpt: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    terminateSwap: TypedContractMethod<
      [seqOfOpt: BigNumberish, seqOfSwap: BigNumberish, ],
      [SwapsRepo.SwapStructOutput],
      'nonpayable'
    >
    

    
    updateOracle: TypedContractMethod<
      [seqOfOpt: BigNumberish, d1: BigNumberish, d2: BigNumberish, d3: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addObligorIntoOption'): TypedContractMethod<
      [seqOfOpt: BigNumberish, obligor: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'allSwapsClosed'): TypedContractMethod<
      [seqOfOpt: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'counterOfOptions'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'counterOfSwaps'): TypedContractMethod<
      [seqOfOpt: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'createOption'): TypedContractMethod<
      [sn: BytesLike, snOfCond: BytesLike, rightholder: BigNumberish, paid: BigNumberish, par: BigNumberish, ],
      [OptionsRepo.HeadStructOutput],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createSwap'): TypedContractMethod<
      [seqOfOpt: BigNumberish, seqOfTarget: BigNumberish, paidOfTarget: BigNumberish, seqOfPledge: BigNumberish, caller: BigNumberish, ],
      [SwapsRepo.SwapStructOutput],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'execOption'): TypedContractMethod<
      [seqOfOpt: BigNumberish, caller: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAllOptions'): TypedContractMethod<
      [],
      [OptionsRepo.OptionStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getAllOraclesOfOption'): TypedContractMethod<
      [seqOfOpt: BigNumberish, ],
      [Checkpoints.CheckpointStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getAllSwapsOfOption'): TypedContractMethod<
      [seqOfOpt: BigNumberish, ],
      [SwapsRepo.SwapStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getLatestOracle'): TypedContractMethod<
      [seqOfOpt: BigNumberish, ],
      [Checkpoints.CheckpointStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getObligorsOfOption'): TypedContractMethod<
      [seqOfOpt: BigNumberish, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getOption'): TypedContractMethod<
      [seqOfOpt: BigNumberish, ],
      [OptionsRepo.OptionStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getOracleAtDate'): TypedContractMethod<
      [seqOfOpt: BigNumberish, date: BigNumberish, ],
      [Checkpoints.CheckpointStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getSeqListOfOptions'): TypedContractMethod<
      [],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getSwap'): TypedContractMethod<
      [seqOfOpt: BigNumberish, seqOfSwap: BigNumberish, ],
      [SwapsRepo.SwapStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'isObligor'): TypedContractMethod<
      [seqOfOpt: BigNumberish, acct: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isOption'): TypedContractMethod<
      [seqOfOpt: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isRightholder'): TypedContractMethod<
      [seqOfOpt: BigNumberish, acct: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isSwap'): TypedContractMethod<
      [seqOfOpt: BigNumberish, seqOfSwap: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'issueOption'): TypedContractMethod<
      [opt: OptionsRepo.OptionStruct, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'payOffSwap'): TypedContractMethod<
      [seqOfOpt: BigNumberish, seqOfSwap: BigNumberish, ],
      [SwapsRepo.SwapStructOutput],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'qtyOfOptions'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'regOptionTerms'): TypedContractMethod<
      [opts: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'removeObligorFromOption'): TypedContractMethod<
      [seqOfOpt: BigNumberish, obligor: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'sumPaidOfTarget'): TypedContractMethod<
      [seqOfOpt: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'terminateSwap'): TypedContractMethod<
      [seqOfOpt: BigNumberish, seqOfSwap: BigNumberish, ],
      [SwapsRepo.SwapStructOutput],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateOracle'): TypedContractMethod<
      [seqOfOpt: BigNumberish, d1: BigNumberish, d2: BigNumberish, d3: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AddObligorIntoOpt'): TypedContractEvent<AddObligorIntoOptEvent.InputTuple, AddObligorIntoOptEvent.OutputTuple, AddObligorIntoOptEvent.OutputObject>;
getEvent(key: 'CreateOpt'): TypedContractEvent<CreateOptEvent.InputTuple, CreateOptEvent.OutputTuple, CreateOptEvent.OutputObject>;
getEvent(key: 'ExecOpt'): TypedContractEvent<ExecOptEvent.InputTuple, ExecOptEvent.OutputTuple, ExecOptEvent.OutputObject>;
getEvent(key: 'IssueOpt'): TypedContractEvent<IssueOptEvent.InputTuple, IssueOptEvent.OutputTuple, IssueOptEvent.OutputObject>;
getEvent(key: 'PayOffSwap'): TypedContractEvent<PayOffSwapEvent.InputTuple, PayOffSwapEvent.OutputTuple, PayOffSwapEvent.OutputObject>;
getEvent(key: 'RegSwap'): TypedContractEvent<RegSwapEvent.InputTuple, RegSwapEvent.OutputTuple, RegSwapEvent.OutputObject>;
getEvent(key: 'RemoveObligorFromOpt'): TypedContractEvent<RemoveObligorFromOptEvent.InputTuple, RemoveObligorFromOptEvent.OutputTuple, RemoveObligorFromOptEvent.OutputObject>;
getEvent(key: 'TerminateSwap'): TypedContractEvent<TerminateSwapEvent.InputTuple, TerminateSwapEvent.OutputTuple, TerminateSwapEvent.OutputObject>;
getEvent(key: 'UpdateOracle'): TypedContractEvent<UpdateOracleEvent.InputTuple, UpdateOracleEvent.OutputTuple, UpdateOracleEvent.OutputObject>;

    filters: {
      
      'AddObligorIntoOpt(uint256,uint256)': TypedContractEvent<AddObligorIntoOptEvent.InputTuple, AddObligorIntoOptEvent.OutputTuple, AddObligorIntoOptEvent.OutputObject>;
      AddObligorIntoOpt: TypedContractEvent<AddObligorIntoOptEvent.InputTuple, AddObligorIntoOptEvent.OutputTuple, AddObligorIntoOptEvent.OutputObject>;
    

      'CreateOpt(uint256,bytes32)': TypedContractEvent<CreateOptEvent.InputTuple, CreateOptEvent.OutputTuple, CreateOptEvent.OutputObject>;
      CreateOpt: TypedContractEvent<CreateOptEvent.InputTuple, CreateOptEvent.OutputTuple, CreateOptEvent.OutputObject>;
    

      'ExecOpt(uint256)': TypedContractEvent<ExecOptEvent.InputTuple, ExecOptEvent.OutputTuple, ExecOptEvent.OutputObject>;
      ExecOpt: TypedContractEvent<ExecOptEvent.InputTuple, ExecOptEvent.OutputTuple, ExecOptEvent.OutputObject>;
    

      'IssueOpt(uint256,uint256)': TypedContractEvent<IssueOptEvent.InputTuple, IssueOptEvent.OutputTuple, IssueOptEvent.OutputObject>;
      IssueOpt: TypedContractEvent<IssueOptEvent.InputTuple, IssueOptEvent.OutputTuple, IssueOptEvent.OutputObject>;
    

      'PayOffSwap(uint256,bytes32)': TypedContractEvent<PayOffSwapEvent.InputTuple, PayOffSwapEvent.OutputTuple, PayOffSwapEvent.OutputObject>;
      PayOffSwap: TypedContractEvent<PayOffSwapEvent.InputTuple, PayOffSwapEvent.OutputTuple, PayOffSwapEvent.OutputObject>;
    

      'RegSwap(uint256,bytes32)': TypedContractEvent<RegSwapEvent.InputTuple, RegSwapEvent.OutputTuple, RegSwapEvent.OutputObject>;
      RegSwap: TypedContractEvent<RegSwapEvent.InputTuple, RegSwapEvent.OutputTuple, RegSwapEvent.OutputObject>;
    

      'RemoveObligorFromOpt(uint256,uint256)': TypedContractEvent<RemoveObligorFromOptEvent.InputTuple, RemoveObligorFromOptEvent.OutputTuple, RemoveObligorFromOptEvent.OutputObject>;
      RemoveObligorFromOpt: TypedContractEvent<RemoveObligorFromOptEvent.InputTuple, RemoveObligorFromOptEvent.OutputTuple, RemoveObligorFromOptEvent.OutputObject>;
    

      'TerminateSwap(uint256,uint256)': TypedContractEvent<TerminateSwapEvent.InputTuple, TerminateSwapEvent.OutputTuple, TerminateSwapEvent.OutputObject>;
      TerminateSwap: TypedContractEvent<TerminateSwapEvent.InputTuple, TerminateSwapEvent.OutputTuple, TerminateSwapEvent.OutputObject>;
    

      'UpdateOracle(uint256,uint256,uint256,uint256)': TypedContractEvent<UpdateOracleEvent.InputTuple, UpdateOracleEvent.OutputTuple, UpdateOracleEvent.OutputObject>;
      UpdateOracle: TypedContractEvent<UpdateOracleEvent.InputTuple, UpdateOracleEvent.OutputTuple, UpdateOracleEvent.OutputObject>;
    
    };
  }