/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BookOfDocs } from './BookOfDocs.js';
export type { BookOfPoints } from './BookOfPoints.js';
export type { BookOfUsers } from './BookOfUsers.js';
export type { IBookOfDocs } from './IBookOfDocs.js';
export type { IBookOfPoints } from './IBookOfPoints.js';
export type { IBookOfUsers } from './IBookOfUsers.js';